/* ============ BİLMECELER VERİSİ ============ */
const bilmeceler = [
  {q:"Yerde sürünür, gökte uçmaz, adı devedir ama devesi yoktur, nedir bu?", a:"Deve dikeni."},
  {q:"Başı var gövdesi yok, kolu var bacağı yok, nedir bu?", a:"Çivi."},
  {q:"Suda yaşar, ağzı yok, yüzer ama balık değildir, nedir bu?", a:"Yosun."},
  {q:"Küçücük kutu, içinde bin nur, nedir bu?", a:"Nar."},
  {q:"Ak koyun kara kuzu yaya gider gölge iz bırakmaz, nedir bu?", a:"Ay ve gece."},
  {q:"Ayakları yerde başı gökte, konuşur ama ağzı yoktur, nedir bu?", a:"Ağaç."},
  {q:"Uzaktan baktım bir taş, yanına vardım dört ayak bir baş, nedir bu?", a:"Kaplumbağa."},
  {q:"Ben giderim o gider, arkamdan tık tık eder, nedir bu?", a:"Baston."},
  {q:"Kanadı var uçamaz, kolları var sarılmaz, rüzgar estikçe döner durur, nedir bu?", a:"Yel değirmeni."},
  {q:"Bir küçücük fıçıcık, içi dolu turşucık, nedir bu?", a:"Limon."},
  {q:"Ağzı var odun yutar, bacası var duman tüter, nedir bu?", a:"Soba."},
  {q:"Uzun uzun uzarlar, boylu boyunca uzanırlar, ne yürürler ne koşarlar, nedir bu?", a:"Yol."},
  {q:"Ayakları yok ama yürür, kolları yok ama sarılır, dilini gösterir ama tatmaz, nedir bu?", a:"Yılan."},
  {q:"Gökte durur paslanmaz, suya düşer ıslanmaz, nedir bu?", a:"Güneş."},
  {q:"Biz biz idik otuz iki kız idik, ezildik büzüldük bir sıraya dizildik, nedir bu?", a:"Dişler."},
  {q:"Dışı kazan karası, içi peynir mayası, nedir bu?", a:"Kestane."},
  {q:"Yarım kaşık, duvara yapışık, nedir bu?", a:"Kulak."},
  {q:"Altı mermer üstü mermer, içinde bir bülbül öter, nedir bu?", a:"Dil."},
  {q:"Bir kapaklı, çok yapraklı, içinde bilgi saklı, nedir bu?", a:"Kitap."},
  {q:"İçini boşaltırsan büyür, doldurursan küçülür, nedir bu?", a:"Çukur."},
  {q:"Gözle görülmez, elle tutulmaz, o olmasa yaşanmaz, nedir bu?", a:"Hava."},
  {q:"Uzaktan baktım bir karaltı, yanına vardım on sekiz altı, nedir bu?", a:"Karınca."},
  {q:"Ayakları var yürüyemez, masası var yemek yiyemez, nedir bu?", a:"Sandalye."},
  {q:"Sarıdır sallanır, dalında ballanır, nedir bu?", a:"Armut."},
  {q:"Dışı yeşil içi kırmızı, ağzımızda sulanır, nedir bu?", a:"Karpuz."},
  {q:"Kuyruğu var canı yok, ipi elde gökte uçar, rüzgarsız yerde durur, nedir bu?", a:"Uçurtma."},
  {q:"Gece gelir tıkır tıkır, gündüz saklanır kıpır kıpır, nedir bu?", a:"Fare."},
  {q:"Uzun yoldan kuş gelir, ne söylese hoş gelir, nedir bu?", a:"Mektup."},
  {q:"Ateşe girer yanmaz, suya girer ıslanmaz, nedir bu?", a:"Gölge."},
  {q:"Gece yürür, gündüz durur, yorulmak nedir bilmez, nedir bu?", a:"Saat."},
  {q:"Dört ayağı var yürüyemez, sırtı var yük taşıyamaz, nedir bu?", a:"Masa."},
  {q:"Çarşıdan aldım kapkara, evde yandı kıpkırmızı, nedir bu?", a:"Kömür."},
  {q:"Gökyüzünde süzülür, kanatları demirden, insan taşır her yere, nedir bu?", a:"Uçak."},
  {q:"Suya düşer ıslanmaz, yere düşer paslanmaz, nedir bu?", a:"Işık."},
  {q:"Ben giderim o kalır, arkamdan izi kalır, nedir bu?", a:"Adım."},
  {q:"Mora çalar rengi, parlar güneşte derisi, sapının tacı yeşildir, nedir bu?", a:"Patlıcan."},
  {q:"İçi boş, ses verir, vurdukça neşelenir, nedir bu?", a:"Davul."},
  {q:"Bağlarsam yürür, çözersem durur, nedir bu?", a:"Ayakkabı."},
  {q:"Yorulmadan yol alır, ne izi kalır ne tozu kalır, nedir bu?", a:"Rüzgar."},
  {q:"Dokunmadan ağlatır, her mutfakta sızlatır, nedir bu?", a:"Soğan."},
  {q:"Sesi var canı yok, konuşur ağzı yok, nedir bu?", a:"Radyo."},
  {q:"Açarsam dünya görür, kaparsam rüya görür, nedir bu?", a:"Göz."},
  {q:"Dağdan gelir taştan gelir, bir kükremiş arslan gelir, nedir bu?", a:"Sel."},
  {q:"Kışın yatar, yazın kalkar, her çiçeğe konup bal yapar, nedir bu?", a:"Arı."},
  {q:"Yer altında kırmızı pancar, nedir bu?", a:"Turp."},
  {q:"Gece gündüz göz kırpar ama hiç uyumaz, nedir bu?", a:"Yıldız."},
  {q:"Biz iki kardeşiz, birbirimizi görmeyiz ama hep yan yanayız, nedir bu?", a:"Gözler."},
  {q:"Elde taşınır, yağmurda açılır, nedir bu?", a:"Şemsiye."},
  {q:"İki camı var, iki kolu var, gözüme oturur, kulağımı tutar, nedir bu?", a:"Gözlük."},
  {q:"Beş parmağı var ama tutmaz, elin şeklini alır ama el değildir, nedir bu?", a:"Eldiven."},
  {q:"Yazın giyinir, kışın soyunur, dökülünce altına halı olur, nedir bu?", a:"Yaprak."},
  {q:"Isıtınca erir, soğutunca sertleşir, hayattır o her canlıya, nedir bu?", a:"Su."},
  {q:"Dokunmadan çalınır, dudakların arasından yükselir, nedir bu?", a:"Islık."},
  {q:"Hangi anahtar hiçbir kilidi açmaz ama her notayı başlatır, nedir bu?", a:"Sol anahtarı."},
  {q:"Yürür yürür iz etmez, hızlı gitse toz etmez, denizde süzülür gider, nedir bu?", a:"Gemi."},
  {q:"Küçük küçük dişleri var, her saçı tek tek tarar, nedir bu?", a:"Tarak."},
  {q:"Ayaksız koşar, kanatsız uçar, gökyüzünde pamuk gibidir, nedir bu?", a:"Bulut."},
  {q:"Dışı var içi yok, dayak yer suçu yok, sahada yuvarlanır durur, nedir bu?", a:"Top."},
  {q:"Her geçen gün azalır ama hiç kimse ne kadar kaldığını bilmez, nedir bu?", a:"Ömür."},
  {q:"Altından evleri var, tatlıdan dilleri var, çalışkanlıkları dillere destan, nedir bu?", a:"Arı kovanı."},
  {q:"Biz ona bakarız, o bize güler, her doğrumuzu yüzümüze söyler, nedir bu?", a:"Ayna."},
  {q:"Bize ışık verir, kendi eriyip gider, eridikçe boyu kısalır, nedir bu?", a:"Mum."},
  {q:"Dört köşesi var, her duvara asılır, içine anılar sığdırılır, nedir bu?", a:"Çerçeve."},
  {q:"Ayaklar altında ezilir, yine de ses çıkarmaz, odayı süsler, nedir bu?", a:"Halı."},
  {q:"Kuyruğu var fare değil, yelesi var aslan değil, kişner ama insan değil, nedir bu?", a:"At."},
  {q:"Bir ağacı oyarlar, içine teller koyarlar, dokunursan ağlarlar, nedir bu?", a:"Saz."},
  {q:"Gelin gibi süzülür, kışın gökten dökülür, bembeyazdır her yer, nedir bu?", a:"Kar."},
  {q:"Kendi beyaz, içi sarı, besler bütün insanları, kahvaltıda sevilir, nedir bu?", a:"Yumurta."},
  {q:"Gece çıkar gökyüzüne, benzer gümüş bir tepsiye, göğün incisidir, nedir bu?", a:"Dolunay."},
  {q:"Dal ucunda tüylü top, yemesi tatlı şerbet, turuncu renkli meyve, nedir bu?", a:"Şeftali."},
  {q:"Ben yazarım o siler, her hatamı temizler, nedir bu?", a:"Silgi."},
  {q:"Gündüz yazar, gece okur, her evde baş köşede oturur, renkli dünyalar sunar, nedir bu?", a:"Televizyon."},
  {q:"Kanatları tül gibi, sesi var bülbül gibi, çiçekleri çok sever, nedir bu?", a:"Kelebek."},
  {q:"Kulağını büktükçe şarkı söyler, yayla çalınır tellidir, nedir bu?", a:"Keman."},
  {q:"Sıcak odada erir, soğuk havada sertleşir, üstünde kayılır, nedir bu?", a:"Buz."},
  {q:"Yazın bizi gölgeler, kışın yakacak olur, ormandan gelir, nedir bu?", a:"Odun."},
  {q:"Arkasında iz bırakır, her yazdığını anlatır, defterin en yakın dostu, nedir bu?", a:"Kalem."},
  {q:"Yarım halka şeklinde, yağmurdan sonra gökte yedi renkle belirir, nedir bu?", a:"Gökkuşağı."},
  {q:"İki tekeri var, motoru yok, pedal çevirirsin gider, nedir bu?", a:"Bisiklet."},
  {q:"Evimizi korur, yabancıya havlar, sadık bir dosttur, nedir bu?", a:"Köpek."},
  {q:"Sütü sevilir, yoğurdu yenir, meler meler kırlarda gezer, nedir bu?", a:"Koyun."},
  {q:"Uzun boylu, ince belli, suyu sever yeşil yapraklı, göğe uzanır, nedir bu?", a:"Kavak ağacı."},
  {q:"Ayakları kürekli, suda yüzer ördek gibi, bembeyaz tüyleri var, nedir bu?", a:"Kaz."},
  {q:"Bir bacağı var, üstünde şemsiyesi var, yağmurdan sonra ormanda biter, nedir bu?", a:"Mantar."},
  {q:"Yol üstünde durur, gelene geçene yön gösterir, nedir bu?", a:"Tabela."},
  {q:"Kat kat katlanır, içi bilgiyle tatlanır, kalemle yazılır, nedir bu?", a:"Defter."},
  {q:"Dört mevsim yeşil kalır, iğne yapraklı dalları var, yılbaşında süslenir, nedir bu?", a:"Çam ağacı."},
  {q:"Kanatları var kuş değil, motoru var uçak değil, dikey yükselir havada, nedir bu?", a:"Helikopter."},
  {q:"Dışı sarı içi beyaz, soyulmadan yenmez, maymunlar çok sever, nedir bu?", a:"Muz."},
  {q:"İki tekerlek üstünde gider, gürültülü ses çıkarır, kaskla binilir, nedir bu?", a:"Motosiklet."},
  {q:"İncecik teli var, kulağına takarsın sesi duyarsın, nedir bu?", a:"Kulaklık."},
  {q:"Tuzu var tadı yok, suyu var balığı yok, ağlayınca dökülür, nedir bu?", a:"Gözyaşı."},
  {q:"Bir düğmeye basarsın, karanlık odayı aydınlatırsın, nedir bu?", a:"Elektrik anahtarı."},
  {q:"İçinde suyu var, dışında tüyleri var, kırarsan sütü çıkar, egzotiktir, nedir bu?", a:"Hindistan cevizi."},
  {q:"Küçücük bir böcektir, ışık saçar gecedir, yanıp söner arkası, nedir bu?", a:"Ateş böceği."},
  {q:"Her sabah uykudan uyandırır, zamanı bize fısıldar, zili çalar, nedir bu?", a:"Çalar saat."},
  {q:"Sarıdır saman gibi, tadı var bal gibi, dilim dilim yenir yazın, nedir bu?", a:"Kavun."},
  {q:"Beslersen büyür ama yemek yemez, susarsa değil susattırırsan ölür, dokunma yakar, nedir bu?", a:"Ateş."},
  {q:"Ağzı var dili yok, karnı var canı yok, yemek pişirir ateşte, nedir bu?", a:"Tencere."},
  {q:"Toprak altında yaşar, köstebek gibi kazar, turuncu renkli kökü var, nedir bu?", a:"Havuç."},
  {q:"Hiç durmadan çalışır, zamanı bize gösterir, bileğimize takarız, nedir bu?", a:"Kol saati."},
  {q:"Boynu uzun bacakları ince, yaprak yer ağaçların tepesinde, beneklidir, nedir bu?", a:"Zürafa."},
  {q:"Siyah bir tahtası var, beyaz tebeşir yazar, okulda ders işlenir, nedir bu?", a:"Yazı tahtası."},
  {q:"Çok yumuşak tüyleri var, evde mırıl mırıl gezer, fareleri yakalar, nedir bu?", a:"Kedi."},
  {q:"Karnı beyaz, sırtı siyah, buzlar üstünde yürür, uçamayan kuştur, nedir bu?", a:"Penguen."},
  {q:"Tavan arasında saklanır, her yeri ağ gibi sarar, sekiz bacağı var, nedir bu?", a:"Örümcek."},
  {q:"Gündüzleri bulutların arkasında saklanır, geceleri gökyüzünü aydınlatır, nedir bu?", a:"Ay."},
  {q:"Kışın pencereleri süsler, beyaz desenler çizer, sıcağı görünce erir, nedir bu?", a:"Kırağı."},
  {q:"Buz üstünde kayar, demir ayakları var, ayak kabısına takılır, nedir bu?", a:"Paten."},
  {q:"Gökten yağar damla damla, toprağı besler canla, şemsiyeyle korunuruz, nedir bu?", a:"Yağmur."},
  {q:"Bir ağacı var dalları yok, yaprağı var çiçeği yok, sokakları aydınlatır, nedir bu?", a:"Direk."},
  {q:"Elde taşınır, kulağa tutulur, her yerden insanı konuşturur, cebimize sığar, nedir bu?", a:"Cep telefonu."},
  {q:"Dişleri var tırnakları yok, yiyecekleri keser ağzı yok, odun keser, nedir bu?", a:"Testere."},
  {q:"Kocaman bir gövdesi var, hortumuyla su püskürtür, kulakları yelpaze, nedir bu?", a:"Fil."},
  {q:"Uzun ince bir teli var, çalınca ses verir, mızrapla dokunulur, telli sazdır, nedir bu?", a:"Bağlama."},
  {q:"Toprak altında saklı sarı altınlar, soyup da kızartırsın lezzeti var, nedir bu?", a:"Patates."},
  {q:"Yere dikeriz büyür, meyve verir sevilir, geleceğe nefestir, nedir bu?", a:"Fidan."},
  {q:"Soğuk havada burnumuzdan çıkar, dumana benzer ama duman değildir, nedir bu?", a:"Nefes."},
  {q:"Eğri büğrü bir yolu var, üstünden tren geçer, demirdendir, nedir bu?", a:"Ray."},
  {q:"Yere düşen sarı yapraklar, rüzgarlı soğuk günler hangi mevsimi anlatır, nedir bu?", a:"Sonbahar."},
  {q:"Sırtında yük taşır, uzun kulakları var, inatçılığıyla bilinir, nedir bu?", a:"Eşek."},
  {q:"Ağaçta yetişir, sert kabuğu var, kırarsın içinden beyne benzer yemiş çıkar, nedir bu?", a:"Ceviz."},
  {q:"Kanadı var kuş değil, uçar ama tüyü yok, geceleri avlanır baş aşağı durur, nedir bu?", a:"Yarasa."},
  {q:"Çok hızlı koşar, ormanların kralıdır, yelesi vardır gücüyle bilinir, nedir bu?", a:"Aslan."},
  {q:"Su üstünde yüzer, rüzgar estikçe gider, beyaz yelkenleri var rüzgarla coşar, nedir bu?", a:"Yelkenli."},
  {q:"İçi boş bir boru, üfleyince ses çıkarır, delikleri var parmakla kapatılır, nedir bu?", a:"Flüt."},
  {q:"Yere düşen her şeyi çeker, gözle görülmez bir gücü var, dünyayı dengede tutar, nedir bu?", a:"Yer çekimi."},
  {q:"Duvarda asılı durur, günleri ayları gösterir, yaprak yaprak koparılır, nedir bu?", a:"Takvim."},
  {q:"Geceleri bizi korur, başımızın altında yumuşacıktır, uykunun dostudur, nedir bu?", a:"Yastık."},
  {q:"Sarı sarı taneleri var, koçan üstünde durur, közde veya haşlanarak yenir, nedir bu?", a:"Mısır."},
  {q:"Gökte durur sıra sıra, geceleri parlar ara ara, yıldızlar kümesidir, nedir bu?", a:"Samanyolu."},
  {q:"Su altında nefes alır, pulları var parıldar, oltayla tutulur, nedir bu?", a:"Balık."},
  {q:"İki parmağın arasına sığar, kara tahta üstünde iz bırakır beyazdır, nedir bu?", a:"Tebeşir."},
  {q:"Yuvarlaktır tekerlek gibi, döner durur dünya gibi, oyun oynatır çocuklara tıkır tıkır, nedir bu?", a:"Bilye."},
  {q:"Yazın bizi serinletir, pervanesi döner durur, rüzgar yapar odada, nedir bu?", a:"Vantilatör."},
  {q:"Küçücük bir metal, kapıyı açar kilitler, cebimizde taşırız, nedir bu?", a:"Anahtar."},
  {q:"Demir raylar üstünde gider, duman çıkararak pof pof eder, vagonları var, nedir bu?", a:"Tren."},
  {q:"Biz konuşuruz o susar, biz susarız o konuşur, dağlarda sesi tekrarlar, nedir bu?", a:"Yankı."},
  {q:"Yerin altında yaşar, körü körüne kazar, toprağı tepe yapar, nedir bu?", a:"Köstebek."},
  {q:"Boynu var başı yok, kolu var eli yok, üstümüze giyeriz düğmelidir, nedir bu?", a:"Gömlek."},
  {q:"Sıcak fırından taze çıkar, her öğün soframızda baş köşede yer alır, nedir bu?", a:"Ekmek."},
  {q:"Elde taşınır, karanlıkta yolu aydınlatır, pille çalışır ışık saçar, nedir bu?", a:"El feneri."},
  {q:"Uçsuz bucaksız mavi bir su, içinde binbir çeşit canlı yaşar, kıyısı kumsaldır, nedir bu?", a:"Deniz."},
  {q:"Bir ağacı var on iki dalı var, her dalında otuz yaprağı var, zamanı böler, nedir bu?", a:"Yıl, aylar ve günler."},
  {q:"Uzun boylu ince bellidir, çay karıştırmaya yarar, küçüktür, nedir bu?", a:"Çay kaşığı."},
  {q:"Her adımda kısalır, dikiş dikerken iğnenin peşinden gider, nedir bu?", a:"İplik."},
  {q:"Ayakları küreklidir, gölde yüzer vak vak der, sarı gagası var, nedir bu?", a:"Ördek."},
  {q:"Küçük küçük gözleri var, un elerken işe yarar, unun pürüzünü alır, nedir bu?", a:"Elek."},
  {q:"Yazın güneşten korur, kışın yağmurdan korur, başımıza takarız siperlidir, nedir bu?", a:"Şapka."},
  {q:"Su dolunca ağırlaşır, boşalınca hafifler, kuyudan su çekmeye yarar, nedir bu?", a:"Kova."},
  {q:"Ağaçta yetişir, kırmızı veya yeşildir, ısırdıkça kütürdetir, vitamini boldur, nedir bu?", a:"Elma."},
  {q:"Dışı sert kabuklu, içi lezzetli yemişli, ormanda sincaplar çok sever çıtır çıtır, nedir bu?", a:"Fındık."},
  {q:"Her evde bulunur, sabahları yüzümüzü yıkayınca kurulanırız yumuşacıktır, nedir bu?", a:"Havlu."},
  {q:"Bir yanı siyah bir yanı beyaz, gecesi gündüzü var, üstünde yaşarız, nedir bu?", a:"Dünya."},
  {q:"Dokununca ses verir, telleri titrer, omuzda taşınır şarkı söylenir, nedir bu?", a:"Gitar."},
  {q:"Duvara asılır, zamanı gösterir, her saat başı tık tık ses verir, nedir bu?", a:"Duvar saati."},
  {q:"Tarladan gelir yeşil, çuvala girer sarı, fırından çıkar ekmek olur, nedir bu?", a:"Buğday."},
  {q:"Tepesinde tüyü var, altında yumurtası var, gıdaklar durur kümeste, nedir bu?", a:"Tavuk."},
  {q:"Suya düşer batmaz, tahtadan yapılır batmaz, kürekle yürütülür denizde, nedir bu?", a:"Sandal."},
  {q:"Sırtında iğneleri var, ama dikiş dikemez, tehlike anında top olur, nedir bu?", a:"Kirpi."},
  {q:"Kapağı var kilidi yok, içi dolu ama hiç yemek yemez, taşınırken sırtına biner, nedir bu?", a:"Kutu."},
  {q:"Bağda biten yeşil yaprak, sarması olur tabak tabak, zeytinyağlısı sevilir, nedir bu?", a:"Asma yaprağı."},
  {q:"Uzun ince bacakları var, havada vızıldar durur, ısırırsa kaşındırır geceleri, nedir bu?", a:"Sivrisinek."},
  {q:"Küçük küçük dişleri var, toprağı ve yaprakları düzeltmeye yarar saplıdır, nedir bu?", a:"Tırmık."},
  {q:"Yazın yemyeşil ağaçlarla kaplı, kışın bembeyaz karla kaplı, zirvesi bulutlarda, nedir bu?", a:"Dağ."},
  {q:"İki ucu sivri ortası düz kumaşları keseriz düzgünce biz, parmağa takılır, nedir bu?", a:"Makas."},
  {q:"Dışı sarı, içi turuncu dilimli, soyulunca mis gibi kokar, kış meyvesidir, nedir bu?", a:"Mandalina."},
  {q:"Sıcak yaz günlerinde soğuk serinlik verir, içine dondurma konur çıtır çıtırdır, nedir bu?", a:"Külah."},
  {q:"Yerin altında yaşar, toprağı havalandırır, pembe ince bir solucandır yararlıdır, nedir bu?", a:"Toprak solucanı."},
  {q:"Sıcak fırında pişer, kokusu tüm sokağı sarar, susamlı çıtır yuvarlaktır çayla yenir, nedir bu?", a:"Simit."},
  {q:"Yere düşer kırılmaz, suya düşer erir, yemeklere tat verir beyazdır, nedir bu?", a:"Tuz."},
  {q:"Dokununca batar iğnesi, yaprağı çok şifalı yeşil bitki, dokunursan yakar, nedir bu?", a:"Isırgan otu."},
  {q:"Uzun boylu bir kuştur, gölde tek bacağı üstünde durur, pembe tüyleri göz alır, nedir bu?", a:"Flamingo."},
  {q:"Sabahları erkenden öter, herkesi uykudan uyandırır ibiklidir, nedir bu?", a:"Horoz."},
  {q:"Dört ayağı var, sırtında semeri var, dağ tepe demeden yük taşır eşeğe benzer, nedir bu?", a:"Katır."},
  {q:"Sofrada herkes onu bekler, pişmeden önce çiğdir, bittiğinde tabak boşalır, nedir bu?", a:"Yemek."},
  {q:"Sarıdır sallanır, tarlada başak başak rüzgarda altın gibi dalgalanır, nedir bu?", a:"Ekin."},
  {q:"Kar üstünde kayar, iki uzun tahta parçasıdır ayağa takılır karda, nedir bu?", a:"Kayak."},
  {q:"Kırmızıdır yeşil yapraklı, salatalarda çok sevilir sulu sulu, sebzedir, nedir bu?", a:"Domates."},
  {q:"Uzun ince boyu var, yeşil renkli gövdesi var, soyunca çıtır çıtır yenir, nedir bu?", a:"Salatalık."},
  {q:"İçi sarı dışı sert dikenli, lifli lifli tatlı ekşi bir tropikal meyvedir, nedir bu?", a:"Ananas."},
  {q:"Suyu sever, her banyoda köpürür, vücudumuzu ve elimizi temizler, nedir bu?", a:"Sabun."},
  {q:"Köpük köpük olur, saçımızı yıkarız banyoda, güzel kokuludur şampuan, nedir bu?", a:"Şampuan."},
  {q:"Bir yanı açık bir yanı kapalı, içine giysilerimizi düzenli asarız odada, nedir bu?", a:"Gardırop."},
  {q:"Ağaçların kuru dallarından yapılır, kuşlar yumurtalarını içinde saklar, nedir bu?", a:"Kuş yuvası."},
  {q:"Gökyüzünde süzülür, rengarenk dev kumaşı var, uçaktan atlayınca açılır, nedir bu?", a:"Paraşüt."},
  {q:"Tırnakları keser, demirden küçük ve keskin bir alettir kişisel bakım için, nedir bu?", a:"Tırnak makası."},
  {q:"Her gün üstüne basarız, sokakları ve yolları kaplar gri siyah renkli taştır, nedir bu?", a:"Asfalt."},
  {q:"İçine yiyecek koyarız, soğuk tutar bozulmasın diye mutfakta uğuldar, nedir bu?", a:"Buzdolabı."},
  {q:"Yassı yuvarlaktır fırında pişer, üstünde erimiş kaşar sucuk ve mantar olur, nedir bu?", a:"Pizza."},
  {q:"İçinde kahve pişer köpüklü, ocak üstünde durur, uzun sapı vardır metaldir, nedir bu?", a:"Cezve."},
  {q:"Yazın kurur kışın akar, dağlardan yüksekten aşağı gürül gürül dökülür, nedir bu?", a:"Şelale."},
  {q:"Mavi gökyüzünde süzülür, süzüldükçe şarkı söyler küçük kanatlı tüylüdür, nedir bu?", a:"Kuş."},
  {q:"Kışın soğukta pencerelerden aşağı sarkar, buzdan mızrak gibidir donmuştur, nedir bu?", a:"Sarkıt."},
  {q:"Sıcak yaz günlerinde deniz kenarında uzanırız üstüne, ince tanelidir sarıdır, nedir bu?", a:"Kum."},
  {q:"Yere gömeriz canlanır, canlandıkça yeşil yaprak açar fidana döner, nedir bu?", a:"Tohum."},
  {q:"Küçük siyah bir boncuk, zeytin ağacından toplanır kahvaltıda yenir, nedir bu?", a:"Zeytin."},
  {q:"İki kardeş yan yana, sallanırlar yeşil dalda, kırmızı sulu meyvedir, nedir bu?", a:"Kiraz."},
  {q:"Yeşildir bazen acıdır, yemeklerin ve salataların vazgeçilmez tacıdır, nedir bu?", a:"Biber."},
  {q:"Altı ateş üstü duman, içinde çay demlenir kokulu her zaman, nedir bu?", a:"Çaydanlık."},
  {q:"Bin gözüm var ama hiçbirini kapatamam, suyu süzerim ama hiç susamam, nedir bu?", a:"Süzgeç."},
  {q:"Ne kadar çok verirsen o kadar azalır, ama hiç vermezsen değeri hiç artmaz, nedir bu?", a:"Zaman."},
  {q:"İki kardeşim var, biri hep önde biri hep arkada, ikimiz de aynı ayakkabıyı giyeriz, nedir bu?", a:"Ayaklar."},
  {q:"Beni yesen açlığın geçmez, beni içsen susuzluğun geçmez, gözünle yer kulağınla içersin, nedir bu?", a:"Müzik."},
  {q:"Dört tekerleği var ama araba değil, oyuncaktır çocuklar sever, ipiyle çekilir, nedir bu?", a:"Oyuncak araba."},
  {q:"Kışın giyilir yazın dolapta kalır, kollu ve yünlüdür, üşütmez, nedir bu?", a:"Kazak."},
  {q:"Sabah kurulur akşam sökülür, üstünde uyuruz her gece, nedir bu?", a:"Yatak."},
  {q:"İçi boştur üflersin ses çıkar, bayramlarda çocuklar çalar, plastiktir, nedir bu?", a:"Düdük."},
  {q:"Uzun bacaklıdır suda yaşamaz, karada avlanır gagası uzundur, beyaz tüylüdür, nedir bu?", a:"Leylek."},
  {q:"Camdandır kırılır ama tutmaz, içine su koyarsın çiçekleri süsler, nedir bu?", a:"Vazo."},
  {q:"Bir bacağı var ama yürüyemez, üstünde ressamlar resim yapar, ahşaptır, nedir bu?", a:"Şövale."},
  {q:"Yuvarlaktır dönmez, ekmeğin üstüne sürülür, yağlıdır kahvaltıda sevilir, nedir bu?", a:"Tereyağı."},
  {q:"Sırtında kabuğu var ama kaplumbağa değil, denizde yaşar yan yan yürür, kıskaçları var, nedir bu?", a:"Yengeç."},
  {q:"Uzun boyunlu bir kaptır, çiçeklere su verir, bahçıvanın en yakın dostudur, nedir bu?", a:"Sulama kabı."},
  {q:"Kışın camlara işlenir buzdan çiçekler gibi, sabahları görülür güneşle kaybolur, nedir bu?", a:"Buz çiçeği."},
  {q:"Odun kırar ama testere değil, sapı uzundur vurarak keser, baltaya benzer, nedir bu?", a:"Balta."},
  {q:"Yuvarlaktır zıplar, ağa girerse sayı olur, ayakla oynanır, nedir bu?", a:"Futbol topu."},
  {q:"Sarı renklidir asılı durur, karanlıkta ışık verir, tavana takılır, nedir bu?", a:"Lamba."},
  {q:"İçinde un var ama fırın değil, hamur açılır üstünde, tahtadır, nedir bu?", a:"Hamur tahtası."},
  {q:"Yaz meyvesidir tatlıdır sulu, çekirdeği vardır ortasında, sarı veya kırmızıdır, nedir bu?", a:"Kayısı."},
  {q:"Gövdesi taş gibi sert, üstünde yosun tutar, denizde dalgalarla oynar, nedir bu?", a:"Kaya."},
  {q:"Bir ucu kalın bir ucu ince, çiviyi çakmaya yarar demirdendir, nedir bu?", a:"Çekiç."},
  {q:"Kanatları vardır ama kuş değil, ışığa yaklaşınca yanar, geceleri uçar, nedir bu?", a:"Güve."},
  {q:"Beyaz sıvıdır inekten sağılır, içilir kahvaltıda sevilir, peynire dönüşür, nedir bu?", a:"Süt."},
  {q:"Kışın kar üstünde bırakılır, insan izine benzer ama hayvanındır, çamurda da görülür, nedir bu?", a:"Ayak izi."},
  {q:"Yuvarlaktır dönmez, sapı vardır elde tutulur, yemek pişirmede kullanılır tahtadır, nedir bu?", a:"Kepçe."},
  {q:"Küçük deliklerle doludur, peynir gibi görünür ama peynir değildir, yıkanmada kullanılır, nedir bu?", a:"Sünger."},
  {q:"Karnı büyük bacakları kısa, suda yüzer karada yürür, geniş ağzı vardır, nedir bu?", a:"Su aygırı."},
  {q:"Yuvarlaktır elde tutulur, üstüne yazı yazılır, silinebilir tahtadan değildir, nedir bu?", a:"Beyaz tahta kalemi."},
  {q:"Karanlıkta parlar gökyüzünde, kuyruğu vardır bazen görünür, hızla geçer kayar, nedir bu?", a:"Kayan yıldız."},
  {q:"Suda yaşar ama balık değildir, kabuğu vardır sırtında taşır, yavaş hareket eder, nedir bu?", a:"Salyangoz."},
  {q:"İçinde tohum var meyve değil, patlatılır ocakta, tuzlu yenir sinemada, nedir bu?", a:"Mısır patlağı."},
  {q:"Uzun kulaklıdır hızlı koşar, havuç sever, sıçrayarak ilerler, nedir bu?", a:"Tavşan."},
  {q:"Kışın üstümüze giyilir şişkindir, tüy veya pamuk doludur, sıcak tutar, nedir bu?", a:"Mont."},
  {q:"Dört ayaklıdır süt verir, çayırda otlar, böğürür, nedir bu?", a:"İnek."},
  {q:"Kağıttan yapılır katlanır, uçurulur rüzgarda gökyüzünde süzülür, renklidir, nedir bu?", a:"Kağıt uçak."},
  {q:"Küçük ve yuvarlaktır tatlıdır, çikolata kaplıdır dışı, içinde fındık olur, nedir bu?", a:"Çikolatalı bonbon."},
  {q:"Uzun bir borudur içinden su akar, evlere su taşır, duvarların içindedir, nedir bu?", a:"Su borusu."},
  {q:"Dört köşelidir düz ve incedir, üstüne resim yapılır boyayla, tuvaldir, nedir bu?", a:"Tuval."},
  {q:"Yeşil renklidir uzun yapraklıdır, salatada yenir sulu ve tazedir, nedir bu?", a:"Marul."},
  {q:"Sırtında hörgücü var, çölde yürür susamaz uzun süre, uzun boyunludur, nedir bu?", a:"Deve."},
  {q:"İnce ve uzundur telleri var, çalınca müzik çıkar, gitardan küçüktür, nedir bu?", a:"Ukulele."},
  {q:"Sabah kahvaltıda yenir, dilim dilim kesilir, kızartılır tereyağla sürülür, nedir bu?", a:"Tost ekmeği."},
  {q:"Su üstünde yürür ama batmaz, ince bacaklıdır böcektir, gölette görülür, nedir bu?", a:"Su böceği."},
  {q:"Yuvarlaktır zıplamaz, tahta zeminde oynanır elle vurulur, filesi var, nedir bu?", a:"Voleybol topu."},
  {q:"Beyaz renklidir yumuşaktır, kar gibi ama yenir, dondurma değildir pamuk şekeri de değildir, sütten yapılır, nedir bu?", a:"Yoğurt."},
  {q:"Kırmızı veya sarıdır çiçektir, dikeni var kokusu güzeldir, aşkın simgesidir, nedir bu?", a:"Gül."},
  {q:"Kağıttan yapılır zarftır, içine mektup konur, pul yapıştırılır, nedir bu?", a:"Zarf."},
  {q:"Kışın soğuk havada takılır boyuna, yünden örülür uzun ve dardır, nedir bu?", a:"Atkı."},
  {q:"Yuvarlaktır elde çevrilir, arabanın önündedir yönü belirler, nedir bu?", a:"Direksiyon."},
  {q:"Sıvıdır tatlıdır arılardan gelir, kahvaltıda ekmeğe sürülür, sarı renklidir, nedir bu?", a:"Bal."},
  {q:"Kağıttan yapılır ince ve uzundur, silgi ucu var yazar, tahtadan da olabilir, nedir bu?", a:"Kurşun kalem."},
  {q:"Kışın camlara buğu yapar, üflenince görünür sonra kaybolur, sıcak nefesten oluşur, nedir bu?", a:"Buğu."},
  {q:"Yeşil renklidir bahçede biter, salatalık gibi ama daha küçüktür, ekşi turşusu olur, nedir bu?", a:"Kornişon."},
  {q:"Dört köşelidir üstü camdır, arabanın önündedir yağmurda silinir, nedir bu?", a:"Ön cam."},
  {q:"Uzun kuyruklu bir hayvandır, ağaçta yaşar fındık toplar, kahverengidir çevik zıplar, nedir bu?", a:"Sincap."},
  {q:"Toprağa gömülür patates gibi ama tatlıdır, turuncu renklidir kabuğu var, nedir bu?", a:"Tatlı patates."},
  {q:"Uzun boyunlu kuştur beyaz tüylü, gölde yüzer zarif hareket eder, boynu S şeklindedir, nedir bu?", a:"Kuğu."},
  {q:"Sıcak havada içilir buzla, şekerli veya şekersiz olur, meyveden sıkılır, nedir bu?", a:"Limonata."},
  {q:"Yuvarlaktır sarı ve kokuludur, dilim dilim kesilir sofrada yenir peynirle, nedir bu?", a:"Kavun dilimi."},
  {q:"Elde taşınır su geçirmez, yağmurda giyilir kapüşonu var, nedir bu?", a:"Yağmurluk."},
  {q:"Beyaz renklidir bulut gibi ama gökyüzünde değildir, koyunun sırtındadır, kırkılır, nedir bu?", a:"Yün."},
  {q:"Yeşil renklidir toplu şekilde büyür, çorbada kullanılır tanelidir küçüktür, nedir bu?", a:"Bezelye."},
  {q:"Elde tutulur ısırılır, dışı çıtır içi yumuşaktır, ekmek çeşididir, nedir bu?", a:"Baget ekmek."},
  {q:"Uzun ince gagalıdır suda balık avlar, mavi tüylü olanı da vardır, hızla dalar, nedir bu?", a:"Yalıçapkını."},
  {q:"Dört tekerleği var motoru yok, iki kişilik olur çocuklar iter, nedir bu?", a:"Bebek arabası."},
  {q:"Kağıttan katlanır uçmaz ama şekil alır, sanat için yapılır Japon kökenlidir, nedir bu?", a:"Origami."},
  {q:"Sıcak günlerde yenir dondurulur, meyveli veya çikolatalıdır, külahta olur, nedir bu?", a:"Dondurma."},
  {q:"Toprağın üstünde biter, kırmızı küçük tanelidir, reçeli yapılır ekşimsi tatlıdır, nedir bu?", a:"Ahududu."},
  {q:"Uzun ve sivridir kağıda batırılır, mürekkep doludur eskiden kullanılırmış, nedir bu?", a:"Dolma kalem."},
  {q:"Kışın çatıdan sarkar, buzdan oluşur güneşte erir, sivri ucu var, nedir bu?", a:"Buz sarkıtı."},
  {q:"Sabah açar akşam kapanır, güneşle konuşur sarı yapraklı, tarlada boy verir, nedir bu?", a:"Ayçiçeği."},
  {q:"Dört mevsim değişmez rengi, kayaların üstünde biter, yosun gibi görünür ama değildir, nedir bu?", a:"Liken."},
  {q:"Kanadı yok ama uçar, motoru var pervanesiz, ipiyle kumanda edilir gökte süzülür, nedir bu?", a:"Uçurtma."},
  {q:"Küçük bir kutuda saklanır, çakınca kıvılcım verir, kamp ateşinde işe yarar, nedir bu?", a:"Çakmak."},
  {q:"Elde tutulur küçüktür, resim çeker anı saklar, düğmesine basılır, nedir bu?", a:"Fotoğraf makinesi."},
  {q:"Yeşil renklidir uzun saplı, bahçede sebze yatağında büyür, salatalık değildir kabak ailesindendir, nedir bu?", a:"Kabak."},
  {q:"İki tarafı sivri uçlu, yün örülürken kullanılır, elde tutulur metaldir, nedir bu?", a:"Örgü şişi."},
  {q:"Küçük bir kapta saklanır, kokusu güzeldir cilde sürülür, banyoda kullanılır, nedir bu?", a:"Losyon."},
  {q:"Yerde sürünmez ama yerde durur, üstüne basılır tozu tutar, kapı önünde beklenir, nedir bu?", a:"Paspas."},
  {q:"Kışın giyilir ayakta durur, su geçirmez lastiktendir, çamurlu yolda kullanılır, nedir bu?", a:"Çizme."},
  {q:"Yuvarlaktır düzdür, üstünde saatler yazar, kolumuza takılmaz masada durur, nedir bu?", a:"Masa saati."},
  {q:"Dışı sert kabuk içi tatlı süt, tropikal ağaçta yetişir kırınca sesi çıkar, nedir bu?", a:"Hindistan cevizi."},
  {q:"Uzun ve incedir bükülür, dikişte kullanılır ama iplik değildir, tokadır saça takılır, nedir bu?", a:"Toka."},
  {q:"Küçük tekerlekleri var iki ayak üstünde durulur, kaldırımda kayarak gidilir, nedir bu?", a:"Kaykay."},
  {q:"Sıcak günlerde giyilir kolsuz ve hafiftir, pamuklu kumaştandır yazlıktır, nedir bu?", a:"Tişört."},
  {q:"Yuvarlaktır düzdür masaya konur, üstünde yemek yenir tabaktan büyüktür, nedir bu?", a:"Tepsi."},
  {q:"Uzun sapı vardır ucunda fırçası, dişleri temizler her sabah kullanılır, nedir bu?", a:"Diş fırçası."},
  {q:"Camdan yapılır şeffaftır, içine su ya da şarap konur, ayaklı olanı da vardır, nedir bu?", a:"Kadeh."},
  {q:"Dört köşelidir katlanır cepte taşınır, burun silinir ya da göz yaşı, kumaştandır, nedir bu?", a:"Mendil."},
  {q:"Yuvarlaktır dönmez sabit durur, üstünde saatler yazmaz ama yön gösterir, nedir bu?", a:"Pusula."},
  {q:"Kışın elimize giyilir, beş ayrı bölmesi var, yünden örülür sıcak tutar, nedir bu?", a:"Eldiven."},
  {q:"Uzun bir çubuktur ucu ince, balık tutmaya yarar oltayla birlikte kullanılır, nedir bu?", a:"Olta kamışı."},
  {q:"Yeşil renklidir küçük tanelidir, salatalarda kullanılır ekşimsi tadı var, kapari değildir zeytin ailesindendir, nedir bu?", a:"Zeytin."},
  {q:"Beyaz ve yumuşaktır, yastık gibi ama küçüktür, kanepede süs olarak durur, nedir bu?", a:"Minder."},
  {q:"Kısa saplıdır yuvarlak başlıdır, dişleri fırçalarken diş macunuyla kullanılır, nedir bu?", a:"Diş fırçası."},
  {q:"Uzun ve dardır kumaştan yapılır, boyuna takılır kravatın altına giyilir, nedir bu?", a:"Gömlek yakası."},
  {q:"Kışın camlara buhar yapar, sıcak çay üstünden yükselir, gözle görülür ama tutulmaz, nedir bu?", a:"Buhar."},
  {q:"Toprakta yetişir yeşil yapraklı, ıspanak gibi ama daha büyük yapraklı, pazıya benzer, nedir bu?", a:"Pazı."},
  {q:"Uzun ve incedir ucu keskin, dikişte kumaş keser ama makas değildir, çizim yapar kağıtta, nedir bu?", a:"Cetvel."},
  {q:"Kırmızı ya da yeşildir küçük ve yuvarlaktır, salatalarda bütün olarak yenir, biberden küçüktür, nedir bu?", a:"Domates."},
  {q:"Ayakta durur uzun boyunludur, çiçek koymaya yarar cam ya da seramiktendir, nedir bu?", a:"Vazo."},
  {q:"Kışın giyilir başımıza, yünlü ve sıcaktır, kulaklarımızı da örter, nedir bu?", a:"Bere."},
  {q:"Küçük bir alettir tırnak keser, metaldendir cebe sığar, kişisel bakımda kullanılır, nedir bu?", a:"Tırnak makası."},
  {q:"Uzun boyunlu bir kaptır su ısıtır, ıslık çalar kaynayınca, mutfakta kullanılır, nedir bu?", a:"Su ısıtıcısı."},
  {q:"Yeşil ve uzun yapraklıdır, çayı yapılır demlenir sıcak içilir, bitkidir, nedir bu?", a:"Çay yaprağı."},
  {q:"Dört köşelidir yumuşaktır, üstüne oturulur kanepe ya da koltukta, kumaş kaplıdır, nedir bu?", a:"Yastık."},
  {q:"Uzun ve ince bir çubuktur, ucunda mıknatıs vardır oyuncak balık tutmaya yarar, nedir bu?", a:"Oyuncak olta."},
  {q:"Kışın buzlanan yollara serpilir, beyaz taneli tuz gibidir ama tuz değildir, kar eritir, nedir bu?", a:"Kar tuzu."},
  {q:"Yuvarlak ve düzdür, üstünde saat rakamları yazar ama duvara asılmaz, cepte taşınır, nedir bu?", a:"Cep saati."},
  {q:"Uzun boyunlu ince gövdelidir, içine şarap konur mantar tıpalıdır, camdandır, nedir bu?", a:"Şarap şişesi."},
  {q:"Küçük ve yuvarlaktır sert kabukludur, kırılır içinden badem çıkar, ağaçta yetişir, nedir bu?", a:"Badem."},
  {q:"Dört köşelidir düz ve incedir, üstüne yemek konur ama tabak değildir, masaya serilir, nedir bu?", a:"Masa örtüsü."},
  {q:"Uzun ve düzdür üstünde harfler var, çocuklar okulda kullanır tahtadan ya da plastiktendir, nedir bu?", a:"Cetvel."},
  {q:"Kışın ellerimizi ısıtır, içine sıcak su konur şişe gibidir, yatakta kullanılır, nedir bu?", a:"Termofor."},
  {q:"Yeşil ve büyük yapraklıdır, sarma yapılır zeytinyağıyla pişer, asma ağacından toplanır, nedir bu?", a:"Asma yaprağı."},
  {q:"Uzun ve incedir iki ucu var, kulağa takılır ses dinlenir kabloludur, nedir bu?", a:"Kulaklık kablosu."},
  {q:"Dört bacaklıdır oturulur, mutfakta ya da salonda bulunur sırt dayanağı yoktur, nedir bu?", a:"Tabure."},
  {q:"Küçük bir kaptır içine baharat konur, mutfak dolabında sıra sıra durur, nedir bu?", a:"Baharatlık."},
  {q:"Yuvarlak ve içi boştur, üflenince müzik çıkar, bayram ve maçlarda çalınır, nedir bu?", a:"Boru."},
  {q:"Uzun ve dardır iki tarafı da açık, çorap gibi ama ayakta giyilmez, kola takılır kolluk gibi, nedir bu?", a:"Kolçak."},
  {q:"Küçük yuvarlak ve sert kabukludur, kahve ağacında yetişir kavrulur öğütülür, nedir bu?", a:"Kahve çekirdeği."},
  {q:"Kışın kapı önüne konur, üstünde ayakkabı silinir tüylü ya da lastiktir, nedir bu?", a:"Paspas."},
  {q:"Uzun boyunlu bir kuştur pembe tüylü, bir bacağı üstünde saatlerce durabilir, gölette yaşar, nedir bu?", a:"Flamingo."},
  {q:"Sarı ve yuvarlaktır, dilim dilim kesilir limonatanın içine konur ekşidir, nedir bu?", a:"Limon."},
  {q:"Beyaz ve yumuşaktır bulut gibi görünür, gökyüzünde süzülür yağmur getirir bazen, nedir bu?", a:"Bulut."},
  {q:"Yeşil ve uzun gövdelidir, suda yaşar nilüfer yanında biter, kurbağalar üstüne konar, nedir bu?", a:"Saz."},
  {q:"Dört ayaklıdır yavaş yürür, sırtında evi vardır tehlikede içine çekilir, nedir bu?", a:"Kaplumbağa."},
  {q:"Uzun ve incedir esnektir, lastik gibi ama ayakkabı bağı değildir, saça takılır, nedir bu?", a:"Saç lastiği."},
  {q:"Küçük yuvarlaktır tatlıdır, çikolata içi vardır dışı sert şekerdir, nedir bu?", a:"Draje."},
  {q:"Kışın camlara resim çizer, yaz gelince kaybolur, buzdan oluşur şeffaftır, nedir bu?", a:"Buz çiçeği."},
  {q:"Uzun kuyruklu küçük bir kemirgendir, peynir sever deliklerde yaşar, tuzağa yakalanır, nedir bu?", a:"Fare."},
  {q:"Yeşil renklidir dikenli sapı var, kırmızı çiçek açar aşkın simgesidir, nedir bu?", a:"Gül."},
  {q:"Dört köşelidir camdandır, içinde balık yüzer su doludur evde durur, nedir bu?", a:"Akvaryum."},
  {q:"Uzun ve sivridir demirdendir, çiviyi tutar çekiçle vurulur, nedir bu?", a:"Çivi."},
  {q:"Küçük ve yuvarlaktır kahverengidir, ağaçtan düşer sincaplar toplar sert kabukludur, nedir bu?", a:"Meşe palamudu."},
  {q:"Beyaz tüylüdür gagası sarı, gölde yüzer vak vak eder, yavrularını arkasında götürür, nedir bu?", a:"Ördek."},
  {q:"Uzun ve düzdür camdandır, ışığı geçirir ama kırılgandır, evin duvarında bulunur, nedir bu?", a:"Pencere."},
  {q:"Küçük ve sarıdır uçar vızıldar, çiçekten çiçeğe konar bal yapar, iğnesi var, nedir bu?", a:"Arı."},
  {q:"Yeşil renklidir yaz meyvesidir, dışı pütürlüdür içi sarıdır tüylüdür, nedir bu?", a:"Kivi."},
  {q:"Dört tekerleği var motoru güçlüdür, yolda hızlı gider yakıt yakar, nedir bu?", a:"Araba."},
  {q:"Uzun boyunlu sarı gagalıdır, suda balık avlar tek bacak üstünde bekler, nedir bu?", a:"Balıkçıl."},
  {q:"Küçük ve beyazdır tatlıdır, kahveye atılır çayda erir tanelidir, nedir bu?", a:"Şeker."},
  {q:"Kırmızı renklidir yuvarlaktır, ağaçta yetişir vitamin C doludur, ısırılır kütürdetir, nedir bu?", a:"Elma."},
  {q:"Uzun ve incedir camdandır, içine sıvı doldurulur laboratuvarda kullanılır, nedir bu?", a:"Deney tüpü."},
  {q:"Dört bacaklıdır yeleli, koşar hızlı biner insan üstüne, kişner ahırda yaşar, nedir bu?", a:"At."},
  {q:"Sarı renklidir üçgen şeklinde, peynir gibi görünür karikatürlerde farelerin sevdiği, nedir bu?", a:"Peynir dilimi."},
  {q:"Uzun ve yeşildir gövdesi sivri, kaktüs ailesindendir dikeni var çölde yetişir, nedir bu?", a:"Kaktüs."},
  {q:"Küçük ve yuvarlaktır beyazdır, tavuktan çıkar kahvaltıda yenir kırılgandır, nedir bu?", a:"Yumurta."},
  {q:"Uzun kollu iki parçadır, kışın giyilir kolları var boyun kısmı yok, nedir bu?", a:"Hırka."},
  {q:"Beyaz ve yumuşaktır pamuk gibidir, tatlıdır çubuğa sarılır lunaparkta satılır, nedir bu?", a:"Pamuk şekeri."},
  {q:"Küçük dört ayaklı bir hayvandır zıplar, kulakları uzundur havuç sever, nedir bu?", a:"Tavşan."},
  {q:"Uzun ve incedir metaldendir, kağıt tutturur masada durur, sıkılınca kağıtları birleştirir, nedir bu?", a:"Zımba."},
  {q:"Sarı ve turuncudur, meyve suyu yapılır kabuğu soyulur dilimlidir, nedir bu?", a:"Portakal."},
  {q:"Yeşil ve küçüktür bahçede biter, salatalarda kullanılır kokusu keskindir, nedir bu?", a:"Maydanoz."},
  {q:"Dört köşelidir ahşaptır, üstünde yemek yenir sandalyeyle kullanılır, nedir bu?", a:"Masa."},
  {q:"Uzun boyunlu ve zarif bir kuştur beyaz tüylü, gölde süzülür boynu kıvrıktır, nedir bu?", a:"Kuğu."},
  {q:"Küçük ve yuvarlaktır kırmızıdır, bahçede yetişir ekşi tadı var vitamin doludur, nedir bu?", a:"Kiraz."},
  {q:"Dört ayaklıdır kocaman gövdesi var, hortumuyla su içer kulakları büyüktür, nedir bu?", a:"Fil."},
  {q:"Uzun ve incedir tahtadandır, ucunda silgisi var yazı yazar kurşundandır, nedir bu?", a:"Kurşun kalem."},
  {q:"Beyaz renklidir soğuktur, kışın yağar çocuklar top yapar kartopu oynar, nedir bu?", a:"Kar."},
  {q:"Küçük ve yeşildir bahçede biter, salatalık ailesindendir uzundur sulu tadı var, nedir bu?", a:"Salatalık."},
  {q:"Dört ayaklıdır siyah beyaz benekli, süt verir çayırda otlar böğürür, nedir bu?", a:"İnek."},
  {q:"Uzun ve incedir kağıttandır, mektup göndermeye yarar pul yapıştırılır, nedir bu?", a:"Zarf."},
  {q:"Sarı renklidir kıvrık şekildedir, maymunlar sever soyulur yenir, nedir bu?", a:"Muz."},
  {q:"Küçük siyah böcektir uçar, gece ışık saçar arkasından, çayırlarda görülür, nedir bu?", a:"Ateş böceği."},
  {q:"Dört köşelidir cam ya da plastiktendir, resim çerçevelenir duvara asılır, nedir bu?", a:"Çerçeve."},
  {q:"Uzun kulaklı bir hayvandır sırtında yük taşır, inatçıdır anırır, nedir bu?", a:"Eşek."},
  {q:"Kırmızı ve yuvarlaktır tatlıdır, yaz meyvesidir çekirdeği var reçeli yapılır, nedir bu?", a:"Çilek."},
  {q:"Uzun ve düzdür metaldendir, kesme işlemi yapar mutfakta kullanılır keskindir, nedir bu?", a:"Bıçak."},
  {q:"Küçük kanatlı böcektir renklidir, çiçekten çiçeğe konar kelebek değildir, nedir bu?", a:"Uğur böceği."},
  {q:"Dört bacaklıdır uzun boyunludur, benekli derisi var ağaç yapraklarını yer, nedir bu?", a:"Zürafa."},
  {q:"Uzun ve incedir plastiktendir, dişleri var saçı tarar elde tutulur, nedir bu?", a:"Tarak."},
  {q:"Küçük ve yuvarlaktır sarıdır, arıdan gelir tatlıdır kahvaltıda sürülür, nedir bu?", a:"Bal."},
  {q:"Dört köşelidir kumaştandır, üstünde uyuruz her gece yastıkla birlikte kullanılır, nedir bu?", a:"Yorgan."},
  {q:"Uzun ve sivridir camdandır, termometrede kullanılır ateşi ölçer, nedir bu?", a:"Termometre."},
  {q:"Beyaz ve kabarıktır tatlıdır, sütten yapılır kahvenin üstüne konur, nedir bu?", a:"Krema."},
  {q:"Küçük ve kırmızıdır acıdır, yemeklere tat katar bahçede yetişir, nedir bu?", a:"Kırmızı biber."},
  {q:"Dört ayaklıdır kürklüdür, kuyruğu tüylüdür ağaçta yaşar fındık toplar, nedir bu?", a:"Sincap."},
  {q:"Uzun ve incedir kumaştandır, boyuna dolanır kışın soğuktan korur, nedir bu?", a:"Atkı."},
  {q:"Sarı renklidir tatlıdır, arıların yaptığı peteklerde saklanır, nedir bu?", a:"Bal peteği."},
  {q:"Küçük ve yeşildir bahçede sürünür, salyangoz gibi ama kabuksuzdur, nedir bu?", a:"Sümüklü böcek."},
  {q:"Dört köşelidir tahtadandır, üstünde ütü yapılır kumaş düzeltilir, nedir bu?", a:"Ütü masası."},
  {q:"Uzun kuyruklu bir kuştur renkli tüylü, konuşmayı taklit eder kafeste yaşar, nedir bu?", a:"Papağan."},
  {q:"Beyaz renklidir soğuktur, dondurmanın içine konur meyveli olur, nedir bu?", a:"Dondurma külahı."},
  {q:"Küçük ve sivridir metaldendir, kumaşa batar dikiş dikilir, nedir bu?", a:"İğne."},
  {q:"Dört ayaklıdır kahverengidir, ormanda yaşar bal sever kışın uyur, nedir bu?", a:"Ayı."},
  {q:"Uzun ve incedir kağıttandır, üstüne yazı yazılır defterin sayfasıdır, nedir bu?", a:"Kağıt."},
  {q:"Sarı renklidir yumuşaktır, tereyağından yapılır ekmeğe sürülür, nedir bu?", a:"Margarin."},
  {q:"Küçük ve yeşildir bahçede biter, bezelye gibi ama daha büyüktür kabukludur, nedir bu?", a:"Bakla."},
  {q:"Dört köşelidir metaldendir, içine yemek konur fırında pişirilir, nedir bu?", a:"Fırın tepsisi."},
  {q:"Uzun boyunlu bir hayvandır çölde yaşar, hörgücünde su depolar susamaz, nedir bu?", a:"Deve."},
  {q:"Beyaz renklidir yumuşaktır, pamuktan yapılır kulak temizlemede kullanılır, nedir bu?", a:"Kulak çubuğu."},
  {q:"Küçük ve sarıdır ekşidir, limon ailesindendir daha küçüktür, nedir bu?", a:"Misket limonu."},
  {q:"Dört ayaklıdır beyaz yünlüdür, meler kırlarda otlar yünü kırkılır, nedir bu?", a:"Koyun."},
  {q:"Uzun ve incedir tahtadandır, üstünde nota yazılır müzik aletidir telli, nedir bu?", a:"Keman."},
  {q:"Sarı renklidir tatlıdır, mısırdan yapılır patlatılır sinemada yenir, nedir bu?", a:"Patlamış mısır."},
  {q:"Küçük ve yuvarlaktır kahverengidir, kakao çekirdeğinden yapılır tatlıdır, nedir bu?", a:"Çikolata."},
  {q:"Dört köşelidir kumaştandır, çamaşırlar içine konur temizlenir, nedir bu?", a:"Çamaşır sepeti."},
  {q:"Uzun kuyruklu bir hayvandır suda yaşar, timsaha benzer ama küçüktür, nedir bu?", a:"Kertenkele."},
  {q:"Beyaz renklidir soğuktur, buzdan yapılır içeceklere atılır, nedir bu?", a:"Buz küpü."},
  {q:"Küçük ve yeşildir bahçede biter, brokoli ailesindendir çiçek gibi görünür, nedir bu?", a:"Karnabahar."},
  {q:"Dört ayaklıdır kahverengidir, çölde yaşar hızlı koşar tilkiye benzer, nedir bu?", a:"Çakal."},
  {q:"Uzun ve incedir plastiktendir, içine su konur spor yaparken taşınır, nedir bu?", a:"Su matarası."},
  {q:"Sarı renklidir yuvarlaktır, peynir ailesindendir deliklidir İsviçre'den gelir, nedir bu?", a:"Gravyer peyniri."},
  {q:"Küçük ve kahverengidir tatlıdır, fındıktan yapılır kahvaltıda sürülür, nedir bu?", a:"Fındık ezmesi."},
  {q:"Dört köşelidir camdandır, içinde reçel saklanır kapağı vardır, nedir bu?", a:"Kavanoz."},
  {q:"Uzun boyunlu bir kuştur beyaz tüylü, gagası uzundur bebek getirdiği söylenir, nedir bu?", a:"Leylek."},
  {q:"Beyaz renklidir soğuktur, süt ürünüdür kaşıkla yenir meyveli olur, nedir bu?", a:"Yoğurt."},
  {q:"Küçük ve kırmızıdır tatlı ekşidir, orman meyvesidir küçük tanelidir, nedir bu?", a:"Yaban mersini."},
  {q:"Dört ayaklıdır siyah beyazdır, Afrika'da yaşar atların akrabasıdır çizgilidir, nedir bu?", a:"Zebra."},
  {q:"Uzun ve incedir kauçuktandır, arabaların tekerleğinde bulunur hava basınçlıdır, nedir bu?", a:"Lastik."},
  {q:"Sarı renklidir yuvarlaktır, ekmek yapımında kullanılır undan yapılır mayalıdır, nedir bu?", a:"Simit."},
  {q:"Küçük ve yeşildir bahçede biter, ıspanak ailesindendir demir doludur, nedir bu?", a:"Ispanak."},
  {q:"Dört köşelidir ahşaptır, üstünde kitap okunur lambası da olabilir, nedir bu?", a:"Çalışma masası."},
  {q:"Uzun kuyruklu bir hayvandır Avustralya'da yaşar, torbasında yavru taşır zıplar, nedir bu?", a:"Kanguru."},
  {q:"Beyaz renklidir soğuktur, dondurulmuş meyve suyu şeklindedir çubuklu yenir, nedir bu?", a:"Dondurma çubuğu."},
  {q:"Küçük ve sarıdır tatlıdır, arı sütünden farklıdır polenle yapılır, nedir bu?", a:"Polen."},
  {q:"Dört ayaklıdır siyahtır Afrika'da yaşar aslana benzer ama daha küçüktür, nedir bu?", a:"Panter."},
  {q:"Uzun ve incedir tahtadandır, ucunda fırçası var boyama yapılır, nedir bu?", a:"Boya fırçası."},
  {q:"Sarı renklidir uzundur, muzdan farklıdır tatlı patatese benzer kızartılır, nedir bu?", a:"Tatlı patates."},
  {q:"Küçük ve kırmızıdır tatlıdır, nardan farklıdır tanelidir ekşimsi tadı var, nedir bu?", a:"Nar tanesi."},
  {q:"Dört köşelidir metaldendir, üstünde ekmek kızartılır iki dilim aynı anda girer, nedir bu?", a:"Ekmek kızartma makinesi."}
];
