/* ============ BİLMECELER VERİSİ ============ */
const bilmeceler = [
  {q:"Yerde sürünür, gökte uçmaz, adı devedir ama devesi yoktur, nedir bu?", a:"Deve dikeni."}, //[span_0](start_span)[span_0](end_span)
  {q:"Başı var gövdesi yok, kolu var bacağı yok, nedir bu?", a:"Çivi."}, //[span_1](start_span)[span_1](end_span)
  {q:"Suda yaşar, ağzı yok, yüzer ama balık değildir, nedir bu?", a:"Yosun."}, //[span_2](start_span)[span_2](end_span)
  {q:"Küçücük kutu, içinde bin nur, nedir bu?", a:"Nar."}, //[span_3](start_span)[span_3](end_span)
  {q:"Ak koyun kara kuzu yaya gider gölge iz bırakmaz, nedir bu?", a:"Ay ve gece."}, //[span_4](start_span)[span_4](end_span)
  {q:"Ayakları yerde başı gökte, konuşur ama ağzı yoktur, nedir bu?", a:"Ağaç."}, //[span_5](start_span)[span_5](end_span)
  {q:"Uzaktan baktım bir taş, yanına vardım dört ayak bir baş, nedir bu?", a:"Kaplumbağa."},
  {q:"Ben giderim o gider, arkamdan tık tık eder, nedir bu?", a:"Baston."},
  {q:"Kanadı var uçamaz, kolları var sarılmaz, rüzgar estikçe döner durur, nedir bu?", a:"Yel değirmeni."},
  {q:"Bir küçücük fıçıcık, içi dolu turşucık, nedir bu?", a:"Limon."},
  {q:"Ağzı var odun yutar, bacası var duman tüter, nedir bu?", a:"Soba."},
  {q:"Uzun uzun uzarlar, boylu boyunca uzanırlar, ne yürürler ne koşarlar, nedir bu?", a:"Yol."},
  {q:"Ayakları yok ama yürür, kolları yok ama sarılır, dilini gösterir ama tatmaz, nedir bu?", a:"Yılan."},
  {q:"Gökte durur paslanmaz, suya düşer ıslanmaz, nedir bu?", a:"Güneş."},
  {q:"Biz biz idik otuz iki kız idik, ezildik büzüldük bir sıraya dizildik, nedir bu?", a:"Dişler."},
  {q:"Dışı kazan karası, içi peynir mayası, nedir bu?", a:"Kestane."},
  {q:"Yarım kaşık, duvara yapışık, nedir bu?", a:"Kulak."},
  {q:"Altı mermer üstü mermer, içinde bir bülbül öter, nedir bu?", a:"Dil."},
  {q:"Bir kapaklı, çok yapraklı, içinde bilgi saklı, nedir bu?", a:"Kitap."},
  {q:"İçini boşaltırsan büyür, doldurursan küçülür, nedir bu?", a:"Çukur."},
  {q:"Gözle görülmez, elle tutulmaz, o olmasa yaşanmaz, nedir bu?", a:"Hava."},
  {q:"Uzaktan baktım bir karaltı, yanına vardım on sekiz altı, nedir bu?", a:"Karınca."},
  {q:"Ayakları var yürüyemez, masası var yemek yiyemez, nedir bu?", a:"Sandalye."},
  {q:"Sarıdır sallanır, dalında ballanır, nedir bu?", a:"Armut."},
  {q:"Dışı yeşil içi kırmızı, ağzımızda sulanır, nedir bu?", a:"Karpuz."},
  {q:"Kuyruğu var canı yok, ipi elde gökte uçar, rüzgarsız yerde durur, nedir bu?", a:"Uçurtma."},
  {q:"Gece gelir tıkır tıkır, gündüz saklanır kıpır kıpır, nedir bu?", a:"Fare."},
  {q:"Uzun yoldan kuş gelir, ne söylese hoş gelir, nedir bu?", a:"Mektup."},
  {q:"Ateşe girer yanmaz, suya girer ıslanmaz, nedir bu?", a:"Gölge."},
  {q:"Gece yürür, gündüz durur, yorulmak nedir bilmez, nedir bu?", a:"Saat."},
  {q:"Dört ayağı var yürüyemez, sırtı var yük taşıyamaz, nedir bu?", a:"Masa."},
  {q:"Çarşıdan aldım kapkara, evde yandı kıpkırmızı, nedir bu?", a:"Kömür."},
  {q:"Gökyüzünde süzülür, kanatları demirden, insan taşır her yere, nedir bu?", a:"Uçak."},
  {q:"Suya düşer ıslanmaz, yere düşer paslanmaz, nedir bu?", a:"Işık."},
  {q:"Ben giderim o kalır, arkamdan izi kalır, nedir bu?", a:"Adım."},
  {q:"Mora çalar rengi, parlar güneşte derisi, sapının tacı yeşildir, nedir bu?", a:"Patlıcan."},
  {q:"İçi boş, ses verir, vurdukça neşelenir, nedir bu?", a:"Davul."},
  {q:"Bağlarsam yürür, çözersem durur, nedir bu?", a:"Ayakkabı."},
  {q:"Yorulmadan yol alır, ne izi kalır ne tozu kalır, nedir bu?", a:"Rüzgar."},
  {q:"Dokunmadan ağlatır, her mutfakta sızlatır, nedir bu?", a:"Soğan."},
  {q:"Sesi var canı yok, konuşur ağzı yok, nedir bu?", a:"Radyo."},
  {q:"Açarsam dünya görür, kaparsam rüya görür, nedir bu?", a:"Göz."},
  {q:"Dağdan gelir taştan gelir, bir kükremiş arslan gelir, nedir bu?", a:"Sel."},
  {q:"Kışın yatar, yazın kalkar, her çiçeğe konup bal yapar, nedir bu?", a:"Arı."},
  {q:"Yer altında kırmızı pancar, nedir bu?", a:"Turp."},
  {q:"Gece gündüz göz kırpar ama hiç uyumaz, nedir bu?", a:"Yıldız."},
  {q:"Biz iki kardeşiz, birbirimizi görmeyiz ama hep yan yanayız, nedir bu?", a:"Gözler."},
  {q:"Elde taşınır, yağmurda açılır, nedir bu?", a:"Şemsiye."},
  {q:"İki camı var, iki kolu var, gözüme oturur, kulağımı tutar, nedir bu?", a:"Gözlük."},
  {q:"Beş parmağı var ama tutmaz, elin şeklini alır ama el değildir, nedir bu?", a:"Eldiven."},
  {q:"Yazın giyinir, kışın soyunur, dökülünce altına halı olur, nedir bu?", a:"Yaprak."},
  {q:"Isıtınca erir, soğutunca sertleşir, hayattır o her canlıya, nedir bu?", a:"Su."},
  {q:"Dokunmadan çalınır, dudakların arasından yükselir, nedir bu?", a:"Islık."},
  {q:"Hangi anahtar hiçbir kilidi açmaz ama her notayı başlatır, nedir bu?", a:"Sol anahtarı."},
  {q:"Yürür yürür iz etmez, hızlı gitse toz etmez, denizde süzülür gider, nedir bu?", a:"Gemi."},
  {q:"Küçük küçük dişleri var, her saçı tek tek tarar, nedir bu?", a:"Tarak."},
  {q:"Ayaksız koşar, kanatsız uçar, gökyüzünde pamuk gibidir, nedir bu?", a:"Bulut."},
  {q:"Dışı var içi yok, dayak yer suçu yok, sahada yuvarlanır durur, nedir bu?", a:"Top."},
  {q:"Her geçen gün azalır ama hiç kimse ne kadar kaldığını bilmez, nedir bu?", a:"Ömür."},
  {q:"Altından evleri var, tatlıdan dilleri var, çalışkanlıkları dillere destan, nedir bu?", a:"Arı kovanı."},
  {q:"Biz ona bakarız, o bize güler, her doğrumuzu yüzümüze söyler, nedir bu?", a:"Ayna."},
  {q:"Bize ışık verir, kendi eriyip gider, eridikçe boyu kısalır, nedir bu?", a:"Mum."},
  {q:"Dört köşesi var, her duvara asılır, içine anılar sığdırılır, nedir bu?", a:"Çerçeve."},
  {q:"Ayaklar altında ezilir, yine de ses çıkarmaz, odayı süsler, nedir bu?", a:"Halı."},
  {q:"Kuyruğu var fare değil, yelesi var aslan değil, kişner ama insan değil, nedir bu?", a:"At."},
  {q:"Bir ağacı oyarlar, içine teller koyarlar, dokunursan ağlarlar, nedir bu?", a:"Saz."},
  {q:"Gelin gibi süzülür, kışın gökten dökülür, bembeyazdır her yer, nedir bu?", a:"Kar."},
  {q:"Kendi beyaz, içi sarı, besler bütün insanları, kahvaltıda sevilir, nedir bu?", a:"Yumurta."},
  {q:"Gece çıkar gökyüzüne, benzer gümüş bir tepsiye, göğün incisidir, nedir bu?", a:"Dolunay."},
  {q:"Dal ucunda tüylü top, yemesi tatlı şerbet, turuncu renkli meyve, nedir bu?", a:"Şeftali."},
  {q:"Ben yazarım o siler, her hatamı temizler, nedir bu?", a:"Silgi."},
  {q:"Gündüz yazar, gece okur, her evde baş köşede oturur, renkli dünyalar sunar, nedir bu?", a:"Televizyon."},
  {q:"Kanatları tül gibi, sesi var bülbül gibi, çiçekleri çok sever, nedir bu?", a:"Kelebek."},
  {q:"Kulağını büktükçe şarkı söyler, yayla çalınır tellidir, nedir bu?", a:"Keman."},
  {q:"Sıcak odada erir, soğuk havada sertleşir, üstünde kayılır, nedir bu?", a:"Buz."},
  {q:"Yazın bizi gölgeler, kışın yakacak olur, ormandan gelir, nedir bu?", a:"Odun."},
  {q:"Arkasında iz bırakır, her yazdığını anlatır, defterin en yakın dostu, nedir bu?", a:"Kalem."},
  {q:"Yarım halka şeklinde, yağmurdan sonra gökte yedi renkle belirir, nedir bu?", a:"Gökkuşağı."},
  {q:"İki tekeri var, motoru yok, pedal çevirirsin gider, nedir bu?", a:"Bisiklet."},
  {q:"Evimizi korur, yabancıya havlar, sadık bir dosttur, nedir bu?", a:"Köpek."},
  {q:"Sütü sevilir, yoğurdu yenir, meler meler kırlarda gezer, nedir bu?", a:"Koyun."},
  {q:"Uzun boylu, ince belli, suyu sever yeşil yapraklı, göğe uzanır, nedir bu?", a:"Kavak ağacı."},
  {q:"Ayakları kürekli, suda yüzer ördek gibi, bembeyaz tüyleri var, nedir bu?", a:"Kaz."},
  {q:"Bir bacağı var, üstünde şemsiyesi var, yağmurdan sonra ormanda biter, nedir bu?", a:"Mantar."},
  {q:"Yol üstünde durur, gelene geçene yön gösterir, nedir bu?", a:"Tabela."},
  {q:"Kat kat katlanır, içi bilgiyle tatlanır, kalemle yazılır, nedir bu?", a:"Defter."},
  {q:"Dört mevsim yeşil kalır, iğne yapraklı dalları var, yılbaşında süslenir, nedir bu?", a:"Çam ağacı."},
  {q:"Kanatları var kuş değil, motoru var uçak değil, dikey yükselir havada, nedir bu?", a:"Helikopter."},
  {q:"Dışı sarı içi beyaz, soyulmadan yenmez, maymunlar çok sever, nedir bu?", a:"Muz."},
  {q:"İki tekerlek üstünde gider, gürültülü ses çıkarır, kaskla binilir, nedir bu?", a:"Motosiklet."},
  {q:"İncecik teli var, kulağına takarsın sesi duyarsın, nedir bu?", a:"Kulaklık."},
  {q:"Tuzu var tadı yok, suyu var balığı yok, ağlayınca dökülür, nedir bu?", a:"Gözyaşı."},
  {q:"Bir düğmeye basarsın, karanlık odayı aydınlatırsın, nedir bu?", a:"Elektrik anahtarı."},
  {q:"İçinde suyu var, dışında tüyleri var, kırarsan sütü çıkar, egzotiktir, nedir bu?", a:"Hindistan cevizi."},
  {q:"Küçücük bir böcektir, ışık saçar gecedir, yanıp söner arkası, nedir bu?", a:"Ateş böceği."},
  {q:"Her sabah uykudan uyandırır, zamanı bize fısıldar, zili çalar, nedir bu?", a:"Çalar saat."},
  {q:"Sarıdır saman gibi, tadı var bal gibi, dilim dilim yenir yazın, nedir bu?", a:"Kavun."},
  {q:"Beslersen büyür ama yemek yemez, susarsa değil susattırırsan ölür, dokunma yakar, nedir bu?", a:"Ateş."},
  {q:"Ağzı var dili yok, karnı var canı yok, yemek pişirir ateşte, nedir bu?", a:"Tencere."},
  {q:"Toprak altında yaşar, köstebek gibi kazar, turuncu renkli kökü var, nedir bu?", a:"Havuç."},
  {q:"Hiç durmadan çalışır, zamanı bize gösterir, bileğimize takarız, nedir bu?", a:"Kol saati."},
  {q:"Boynu uzun bacakları ince, yaprak yer ağaçların tepesinde, beneklidir, nedir bu?", a:"Zürafa."},
  {q:"Siyah bir tahtası var, beyaz tebeşir yazar, okulda ders işlenir, nedir bu?", a:"Yazı tahtası."},
  {q:"Çok yumuşak tüyleri var, evde mırıl mırıl gezer, fareleri yakalar, nedir bu?", a:"Kedi."},
  {q:"Karnı beyaz, sırtı siyah, buzlar üstünde yürür, uçamayan kuştur, nedir bu?", a:"Penguen."},
  {q:"Tavan arasında saklanır, her yeri ağ gibi sarar, sekiz bacağı var, nedir bu?", a:"Örümcek."},
  {q:"Gündüzleri bulutların arkasında saklanır, geceleri gökyüzünü aydınlatır, nedir bu?", a:"Ay."},
  {q:"Kışın pencereleri süsler, beyaz desenler çizer, sıcağı görünce erir, nedir bu?", a:"Kırağı."},
  {q:"Buz üstünde kayar, demir ayakları var, ayak kabısına takılır, nedir bu?", a:"Paten."},
  {q:"Gökten yağar damla damla, toprağı besler canla, şemsiyeyle korunuruz, nedir bu?", a:"Yağmur."},
  {q:"Bir ağacı var dalları yok, yaprağı var çiçeği yok, sokakları aydınlatır, nedir bu?", a:"Direk."},
  {q:"Elde taşınır, kulağa tutulur, her yerden insanı konuşturur, cebimize sığar, nedir bu?", a:"Cep telefonu."},
  {q:"Dişleri var tırnakları yok, yiyecekleri keser ağzı yok, odun keser, nedir bu?", a:"Testere."},
  {q:"Kocaman bir gövdesi var, hortumuyla su püskürtür, kulakları yelpaze, nedir bu?", a:"Fil."},
  {q:"Uzun ince bir teli var, çalınca ses verir, mızrapla dokunulur, telli sazdır, nedir bu?", a:"Bağlama."},
  {q:"Toprak altında saklı sarı altınlar, soyup da kızartırsın lezzeti var, nedir bu?", a:"Patates."},
  {q:"Yere dikeriz büyür, meyve verir sevilir, geleceğe nefestir, nedir bu?", a:"Fidan."},
  {q:"Soğuk havada burnumuzdan çıkar, dumana benzer ama duman değildir, nedir bu?", a:"Nefes."},
  {q:"Eğri büğrü bir yolu var, üstünden tren geçer, demirdendir, nedir bu?", a:"Ray."},
  {q:"Yere düşen sarı yapraklar, rüzgarlı soğuk günler hangi mevsimi anlatır, nedir bu?", a:"Sonbahar."},
  {q:"Sırtında yük taşır, uzun kulakları var, inatçılığıyla bilinir, nedir bu?", a:"Eşek."},
  {q:"Ağaçta yetişir, sert kabuğu var, kırarsın içinden beyne benzer yemiş çıkar, nedir bu?", a:"Ceviz."},
  {q:"Kanadı var kuş değil, uçar ama tüyü yok, geceleri avlanır baş aşağı durur, nedir bu?", a:"Yarasa."},
  {q:"Çok hızlı koşar, ormanların kralıdır, yelesi vardır gücüyle bilinir, nedir bu?", a:"Aslan."},
  {q:"Su üstünde yüzer, rüzgar estikçe gider, beyaz yelkenleri var rüzgarla coşar, nedir bu?", a:"Yelkenli."},
  {q:"İçi boş bir boru, üfleyince ses çıkarır, delikleri var parmakla kapatılır, nedir bu?", a:"Flüt."},
  {q:"Yere düşen her şeyi çeker, gözle görülmez bir gücü var, dünyayı dengede tutar, nedir bu?", a:"Yer çekimi."},
  {q:"Duvarda asılı durur, günleri ayları gösterir, yaprak yaprak koparılır, nedir bu?", a:"Takvim."},
  {q:"Geceleri bizi korur, başımızın altında yumuşacıktır, uykunun dostudur, nedir bu?", a:"Yastık."},
  {q:"Sarı sarı taneleri var, koçan üstünde durur, közde veya haşlanarak yenir, nedir bu?", a:"Mısır."},
  {q:"Gökte durur sıra sıra, geceleri parlar ara ara, yıldızlar kümesidir, nedir bu?", a:"Samanyolu."},
  {q:"Su altında nefes alır, pulları var parıldar, oltayla tutulur, nedir bu?", a:"Balık."},
  {q:"İki parmağın arasına sığar, kara tahta üstünde iz bırakır beyazdır, nedir bu?", a:"Tebeşir."},
  {q:"Yuvarlaktır tekerlek gibi, döner durur dünya gibi, oyun oynatır çocuklara tıkır tıkır, nedir bu?", a:"Bilye."},
  {q:"Yazın bizi serinletir, pervanesi döner durur, rüzgar yapar odada, nedir bu?", a:"Vantilatör."},
  {q:"Küçücük bir metal, kapıyı açar kilitler, cebimizde taşırız, nedir bu?", a:"Anahtar."},
  {q:"Demir raylar üstünde gider, duman çıkararak pof pof eder, vagonları var, nedir bu?", a:"Tren."},
  {q:"Biz konuşuruz o susar, biz susarız o konuşur, dağlarda sesi tekrarlar, nedir bu?", a:"Yankı."},
  {q:"Yerin altında yaşar, körü körüne kazar, toprağı tepe yapar, nedir bu?", a:"Köstebek."},
  {q:"Boynu var başı yok, kolu var eli yok, üstümüze giyeriz düğmelidir, nedir bu?", a:"Gömlek."},
  {q:"Sıcak fırından taze çıkar, her öğün soframızda baş köşede yer alır, nedir bu?", a:"Ekmek."},
  {q:"Elde taşınır, karanlıkta yolu aydınlatır, pille çalışır ışık saçar, nedir bu?", a:"El feneri."},
  {q:"Uçsuz bucaksız mavi bir su, içinde binbir çeşit canlı yaşar, kıyısı kumsaldır, nedir bu?", a:"Deniz."},
  {q:"Bir ağacı var on iki dalı var, her dalında otuz yaprağı var, zamanı böler, nedir bu?", a:"Yıl, aylar ve günler."},
  {q:"Uzun boylu ince bellidir, çay karıştırmaya yarar, küçüktür, nedir bu?", a:"Çay kaşığı."},
  {q:"Her adımda kısalır, dikiş dikerken iğnenin peşinden gider, nedir bu?", a:"İplik."},
  {q:"Ayakları küreklidir, gölde yüzer vak vak der, sarı gagası var, nedir bu?", a:"Ördek."},
  {q:"Küçük küçük gözleri var, un elerken işe yarar, unun pürüzünü alır, nedir bu?", a:"Elek."},
  {q:"Yazın güneşten korur, kışın yağmurdan korur, başımıza takarız siperlidir, nedir bu?", a:"Şapka."},
  {q:"Su dolunca ağırlaşır, boşalınca hafifler, kuyudan su çekmeye yarar, nedir bu?", a:"Kova."},
  {q:"Ağaçta yetişir, kırmızı veya yeşildir, ısırdıkça kütürdetir, vitamini boldur, nedir bu?", a:"Elma."},
  {q:"Dışı sert kabuklu, içi lezzetli yemişli, ormanda sincaplar çok sever çıtır çıtır, nedir bu?", a:"Fındık."},
  {q:"Her evde bulunur, sabahları yüzümüzü yıkayınca kurulanırız yumuşacıktır, nedir bu?", a:"Havlu."},
  {q:"Bir yanı siyah bir yanı beyaz, gecesi gündüzü var, üstünde yaşarız, nedir bu?", a:"Dünya."},
  {q:"Dokununca ses verir, telleri titrer, omuzda taşınır şarkı söylenir, nedir bu?", a:"Gitar."},
  {q:"Duvara asılır, zamanı gösterir, her saat başı tık tık ses verir, nedir bu?", a:"Duvar saati."},
  {q:"Tarladan gelir yeşil, çuvala girer sarı, fırından çıkar ekmek olur, nedir bu?", a:"Buğday."},
  {q:"Tepesinde tüyü var, altında yumurtası var, gıdaklar durur kümeste, nedir bu?", a:"Tavuk."},
  {q:"Suya düşer batmaz, tahtadan yapılır batmaz, kürekle yürütülür denizde, nedir bu?", a:"Sandal."},
  {q:"Sırtında iğneleri var, ama dikiş dikemez, tehlike anında top olur, nedir bu?", a:"Kirpi."},
  {q:"Kapağı var kilidi yok, içi dolu ama hiç yemek yemez, taşınırken sırtına biner, nedir bu?", a:"Kutu."},
  {q:"Bağda biten yeşil yaprak, sarması olur tabak tabak, zeytinyağlısı sevilir, nedir bu?", a:"Asma yaprağı."},
  {q:"Uzun ince bacakları var, havada vızıldar durur, ısırırsa kaşındırır geceleri, nedir bu?", a:"Sivrisinek."},
  {q:"Küçük küçük dişleri var, toprağı ve yaprakları düzeltmeye yarar saplıdır, nedir bu?", a:"Tırmık."},
  {q:"Yazın yemyeşil ağaçlarla kaplı, kışın bembeyaz karla kaplı, zirvesi bulutlarda, nedir bu?", a:"Dağ."},
  {q:"İki ucu sivri ortası düz kumaşları keseriz düzgünce biz, parmağa takılır, nedir bu?", a:"Makas."},
  {q:"Dışı sarı, içi turuncu dilimli, soyulunca mis gibi kokar, kış meyvesidir, nedir bu?", a:"Mandalina."},
  {q:"Sıcak yaz günlerinde soğuk serinlik verir, içine dondurma konur çıtır çıtırdır, nedir bu?", a:"Külah."},
  {q:"Yerin altında yaşar, toprağı havalandırır, pembe ince bir solucandır yararlıdır, nedir bu?", a:"Toprak solucanı."},
  {q:"Sıcak fırında pişer, kokusu tüm sokağı sarar, susamlı çıtır yuvarlaktır çayla yenir, nedir bu?", a:"Simit."},
  {q:"Yere düşer kırılmaz, suya düşer erir, yemeklere tat verir beyazdır, nedir bu?", a:"Tuz."},
  {q:"Dokununca batar iğnesi, yaprağı çok şifalı yeşil bitki, dokunursan yakar, nedir bu?", a:"Isırgan otu."},
  {q:"Uzun boylu bir kuştur, gölde tek bacağı üstünde durur, pembe tüyleri göz alır, nedir bu?", a:"Flamingo."},
  {q:"Sabahları erkenden öter, herkesi uykudan uyandırır ibiklidir, nedir bu?", a:"Horoz."},
  {q:"Dört ayağı var, sırtında semeri var, dağ tepe demeden yük taşır eşeğe benzer, nedir bu?", a:"Katır."},
  {q:"Sofrada herkes onu bekler, pişmeden önce çiğdir, bittiğinde tabak boşalır, nedir bu?", a:"Yemek."},
  {q:"Sarıdır sallanır, tarlada başak başak rüzgarda altın gibi dalgalanır, nedir bu?", a:"Ekin."},
  {q:"Kar üstünde kayar, iki uzun tahta parçasıdır ayağa takılır karda, nedir bu?", a:"Kayak."},
  {q:"Kırmızıdır yeşil yapraklı, salatalarda çok sevilir sulu sulu, sebzedir, nedir bu?", a:"Domates."},
  {q:"Uzun ince boyu var, yeşil renkli gövdesi var, soyunca çıtır çıtır yenir, nedir bu?", a:"Salatalık."},
  {q:"İçi sarı dışı sert dikenli, lifli lifli tatlı ekşi bir tropikal meyvedir, nedir bu?", a:"Ananas."},
  {q:"Suyu sever, her banyoda köpürür, vücudumuzu ve elimizi temizler, nedir bu?", a:"Sabun."},
  {q:"Köpük köpük olur, saçımızı yıkarız banyoda, güzel kokuludur şampuan, nedir bu?", a:"Şampuan."},
  {q:"Bir yanı açık bir yanı kapalı, içine giysilerimizi düzenli asarız odada, nedir bu?", a:"Gardırop."},
  {q:"Ağaçların kuru dallarından yapılır, kuşlar yumurtalarını içinde saklar, nedir bu?", a:"Kuş yuvası."},
  {q:"Gökyüzünde süzülür, rengarenk dev kumaşı var, uçaktan atlayınca açılır, nedir bu?", a:"Paraşüt."},
  {q:"Tırnakları keser, demirden küçük ve keskin bir alettir kişisel bakım için, nedir bu?", a:"Tırnak makası."},
  {q:"Her gün üstüne basarız, sokakları ve yolları kaplar gri siyah renkli taştır, nedir bu?", a:"Asfalt."},
  {q:"İçine yiyecek koyarız, soğuk tutar bozulmasın diye mutfakta uğuldar, nedir bu?", a:"Buzdolabı."},
  {q:"Yassı yuvarlaktır fırında pişer, üstünde erimiş kaşar sucuk ve mantar olur, nedir bu?", a:"Pizza."},
  {q:"İçinde kahve pişer köpüklü, ocak üstünde durur, uzun sapı vardır metaldir, nedir bu?", a:"Cezve."},
  {q:"Yazın kurur kışın akar, dağlardan yüksekten aşağı gürül gürül dökülür, nedir bu?", a:"Şelale."},
  {q:"Mavi gökyüzünde süzülür, süzüldükçe şarkı söyler küçük kanatlı tüylüdür, nedir bu?", a:"Kuş."},
  {q:"Kışın soğukta pencerelerden aşağı sarkar, buzdan mızrak gibidir donmuştur, nedir bu?", a:"Sarkıt."},
  {q:"Sıcak yaz günlerinde deniz kenarında uzanırız üstüne, ince tanelidir sarıdır, nedir bu?", a:"Kum."},
  {q:"Yere gömeriz canlanır, canlandıkça yeşil yaprak açar fidana döner, nedir bu?", a:"Tohum."},
  {q:"Küçük siyah bir boncuk, zeytin ağacından toplanır kahvaltıda yenir, nedir bu?", a:"Zeytin."},
  {q:"İki kardeş yan yana, sallanırlar yeşil dalda, kırmızı sulu meyvedir, nedir bu?", a:"Kiraz."},
  {q:"Yeşildir bazen acıdır, yemeklerin ve salataların vazgeçilmez tacıdır, nedir bu?", a:"Biber."},
  {q:"Altı ateş üstü duman, içinde çay demlenir kokulu her zaman, nedir bu?", a:"Çaydanlık."},
  {q:"Başım büyür ayaklarım çürür, kesilirim ama canım yanmaz, salatanın gizli kahramanıyım, nedir bu?", a:"Soğan."},
  {q:"Beni yaksan da alevim olmaz, üstüme bassan sesim çıkar, kışın yağar yazın eririm, nedir bu?", a:"Kar."},
  {q:"Bin gözüm var ama hiçbirini kapatamam, suyu süzerim ama hiç susamam, nedir bu?", a:"Süzgeç."},
  {q:"Ne kadar çok verirsen o kadar azalır, ama hiç vermezsen değeri hiç artmaz, nedir bu?", a:"Zaman."},
  {q:"Herkes benden kaçar ama beni hep taşır, gölgemi hiç bırakmam, güneş çıkınca doğarım, nedir bu?", a:"Gölge."},
  {q:"Beni kırarsan ağlarım, beni açarsan gülerim, sırrını sana ilk söyleyenim, nedir bu?", a:"Mektup."},
  {q:"İki kardeşim var, biri hep önde biri hep arkada, ikimiz de aynı ayakkabıyı giyeriz, nedir bu?", a:"Ayaklar."},
  {q:"Beni yesen açlığın geçmez, beni içsen susuzluğun geçmez, gözünle yer kulağınla içersin, nedir bu?", a:"Müzik."},
  {q:"Rengim yok ama her rengi gösteririm, sesim yok ama her sesi taşırım, kırılırsam yansımam biter, nedir bu?", a:"Ayna."},

  {q:"Dört tekerleği var ama araba değil, oyuncaktır çocuklar sever, ipiyle çekilir, nedir bu?", a:"Oyuncak araba."},
  {q:"Renk renk taneleri var, yağmurdan sonra gökte belirir ama elle tutulmaz, nedir bu?", a:"Gökkuşağı."},
  {q:"İki eli var ama tutmaz, bir yüzü var ama gülmez, duvarda asılı zamanı gösterir, nedir bu?", a:"Duvar saati."},
  {q:"Kışın giyilir yazın dolapta kalır, kollu ve yünlüdür, üşütmez, nedir bu?", a:"Kazak."},
  {q:"Sabah kurulur akşam sökülür, üstünde uyuruz her gece, nedir bu?", a:"Yatak."},
  {q:"Bir ucu sivri bir ucu düz, kağıda batırınca iz bırakır, boyalıdır, nedir bu?", a:"Kalem."},
  {q:"Yuvarlaktır ama top değil, üstünde rakamlar yazar, saate benzer ama duvarda değil, nedir bu?", a:"Kol saati."},
  {q:"İçi boştur üflersin ses çıkar, bayramlarda çocuklar çalar, plastiktir, nedir bu?", a:"Düdük."},
  {q:"Uzun bacaklıdır suda yaşamaz, karada avlanır gagası uzundur, beyaz tüylüdür, nedir bu?", a:"Leylek."},
  {q:"Kışın beyaza bürünür yazın yeşile döner, eteğinde köyler kurulur, zirvesi sisli olur, nedir bu?", a:"Dağ."},
  {q:"Camdandır kırılır ama tutmaz, içine su koyarsın çiçekleri süsler, nedir bu?", a:"Vazo."},
  {q:"Renksiz akar, gökten yağar, bitkileri besler, denizi doldurur, nedir bu?", a:"Su."},
  {q:"Bir bacağı var ama yürüyemez, üstünde ressamlar resim yapar, ahşaptır, nedir bu?", a:"Şövale."},
  {q:"Yuvarlaktır dönmez, ekmeğin üstüne sürülür, yağlıdır kahvaltıda sevilir, nedir bu?", a:"Tereyağı."},
  {q:"Sırtında kabuğu var ama kaplumbağa değil, denizde yaşar yan yan yürür, kıskaçları var, nedir bu?", a:"Yengeç."},
  {q:"Uzun boyunlu bir kaptır, çiçeklere su verir, bahçıvanın en yakın dostudur, nedir bu?", a:"Sulama kabı."},
  {q:"Kışın camlara işlenir buzdan çiçekler gibi, sabahları görülür güneşle kaybolur, nedir bu?", a:"Buz çiçeği."},
  {q:"Deriden yapılır ayağa giyilir, bağcıkları var, yürürken ses çıkarmaz, nedir bu?", a:"Ayakkabı."},
  {q:"Odun kırar ama testere değil, sapı uzundur vurarak keser, baltaya benzer, nedir bu?", a:"Balta."},
  {q:"Yuvarlaktır zıplar, ağa girerse sayı olur, ayakla oynanır, nedir bu?", a:"Futbol topu."},
  {q:"Uçar ama kuş değil, motoru yoktur rüzgarla süzülür, ipiyle uçurulur, nedir bu?", a:"Uçurtma."},
  {q:"Sarı renklidir asılı durur, karanlıkta ışık verir, tavana takılır, nedir bu?", a:"Lamba."},
  {q:"İçinde un var ama fırın değil, hamur açılır üstünde, tahtadır, nedir bu?", a:"Hamur tahtası."},
  {q:"Dokuz canı olduğu söylenir, geceleri gözleri parlar, miyavlar, nedir bu?", a:"Kedi."},
  {q:"Yaz meyvesidir tatlıdır sulu, çekirdeği vardır ortasında, sarı veya kırmızıdır, nedir bu?", a:"Kayısı."},
  {q:"Elde tutulur el yıkanır, köpürür kokuludur, banyoda bulunur, nedir bu?", a:"Sabun."},
  {q:"Gövdesi taş gibi sert, üstünde yosun tutar, denizde dalgalarla oynar, nedir bu?", a:"Kaya."},
  {q:"Dışı yeşil dikenli, içi beyaz sulu, yazın çok sevilir tarlada yetişir, nedir bu?", a:"Kavun."},
  {q:"Bir ucu kalın bir ucu ince, çiviyi çakmaya yarar demirdendir, nedir bu?", a:"Çekiç."},
  {q:"Kanatları vardır ama kuş değil, ışığa yaklaşınca yanar, geceleri uçar, nedir bu?", a:"Güve."},
  {q:"Beyaz sıvıdır inekten sağılır, içilir kahvaltıda sevilir, peynire dönüşür, nedir bu?", a:"Süt."},
  {q:"Kışın kar üstünde bırakılır, insan izine benzer ama hayvanındır, çamurda da görülür, nedir bu?", a:"Ayak izi."},
  {q:"Yuvarlaktır dönmez, sapı vardır elde tutulur, yemek pişirmede kullanılır tahtadır, nedir bu?", a:"Kepçe."},
  {q:"Küçük deliklerle doludur, peynir gibi görünür ama peynir değildir, yıkanmada kullanılır, nedir bu?", a:"Sünger."},
  {q:"Karnı büyük bacakları kısa, suda yüzer karada yürür, geniş ağzı vardır, nedir bu?", a:"Su aygırı."},
  {q:"Sabah çıkar akşam batar, sıcaklık verir ışık saçar, gökyüzünün ortasındadır, nedir bu?", a:"Güneş."},
  {q:"Kışın ellere takılır sıcak tutar, yünden örülür beş parmağı yoktur bazen, nedir bu?", a:"Eldiven."},
  {q:"Uzun ve incedir toprağa dikilir, sonbaharda meyve verir, gövdesi odunsudur, nedir bu?", a:"Fidan."},
  {q:"Küçüktür kanatlıdır, çiçekten çiçeğe konar, bal yapmaz ama tozlaştırır, rengarenktir, nedir bu?", a:"Kelebek."},
  {q:"Dört köşelidir düzdür, üstünde yemek yenir, sandalyeyle birlikte kullanılır, nedir bu?", a:"Masa."},
  {q:"Yuvarlaktır elde tutulur, üstüne yazı yazılır, silinebilir tahtadan değildir, nedir bu?", a:"Beyaz tahta kalemi."},
  {q:"Karanlıkta parlar gökyüzünde, kuyruğu vardır bazen görünür, hızla geçer kayar, nedir bu?", a:"Kayan yıldız."},
  {q:"Suda yaşar ama balık değildir, kabuğu vardır sırtında taşır, yavaş hareket eder, nedir bu?", a:"Salyangoz."},
  {q:"Beyaz tüylüdür gagası sarı, çiftlikte yaşar sabah öter horoz değildir, nedir bu?", a:"Kaz."},
  {q:"İçinde tohum var meyve değil, patlatılır ocakta, tuzlu yenir sinemada, nedir bu?", a:"Mısır patlağı."},
  {q:"Kırmızı veya sarıdır, ağaçta yetişir, kütürdeyerek yenir, kabuğu parlaktır, nedir bu?", a:"Elma."},
  {q:"Dört mevsim değişir yaprağı, ilkbaharda çiçek açar, gövdesi kalındır, nedir bu?", a:"Ağaç."},
  {q:"Camdan yapılır içine bakılır, arkası sırlıdır, kendimizi görürüz, nedir bu?", a:"Ayna."},
  {q:"Uzun kulaklıdır hızlı koşar, havuç sever, sıçrayarak ilerler, nedir bu?", a:"Tavşan."},
  {q:"Yuvarlaktır sarı renklidir, tavada kızarır kahvaltıda yenir, sarısı ortadadır, nedir bu?", a:"Yumurta."},
  {q:"Bacaksızdır sürünür, dilini çıkarır, zehirli olanı da vardır, derisini değiştirir, nedir bu?", a:"Yılan."},
  {q:"Kışın üstümüze giyilir şişkindir, tüy veya pamuk doludur, sıcak tutar, nedir bu?", a:"Mont."},
  {q:"Dört ayaklıdır süt verir, çayırda otlar, böğürür, nedir bu?", a:"İnek."},
  {q:"Suyu emer kurutur, banyoda kullanılır, yumuşaktır katlanır, nedir bu?", a:"Havlu."},
  {q:"Kağıttan yapılır katlanır, uçurulur rüzgarda gökyüzünde süzülür, renklidir, nedir bu?", a:"Kağıt uçak."},
  {q:"Küçük ve yuvarlaktır tatlıdır, çikolata kaplıdır dışı, içinde fındık olur, nedir bu?", a:"Çikolatalı bonbon."},
  {q:"Toprağa ekilir sulanır, yeşerir zamanla büyür, çiçek veya sebze olur, nedir bu?", a:"Tohum."},
  {q:"Uzun bir borudur içinden su akar, evlere su taşır, duvarların içindedir, nedir bu?", a:"Su borusu."},
  {q:"Dört köşelidir düz ve incedir, üstüne resim yapılır boyayla, tuvaldir, nedir bu?", a:"Tuval."},
  {q:"Yeşil renklidir uzun yapraklıdır, salatada yenir sulu ve tazedir, nedir bu?", a:"Marul."},
  {q:"Toprağın altında büyür, turuncu renklidir tavşanlar sever, vitamini boldur, nedir bu?", a:"Havuç."},
  {q:"Sırtında hörgücü var, çölde yürür susamaz uzun süre, uzun boyunludur, nedir bu?", a:"Deve."},
  {q:"İnce ve uzundur telleri var, çalınca müzik çıkar, gitardan küçüktür, nedir bu?", a:"Ukulele."},
  {q:"Sabah kahvaltıda yenir, dilim dilim kesilir, kızartılır tereyağla sürülür, nedir bu?", a:"Tost ekmeği."},
  {q:"Su üstünde yürür ama batmaz, ince bacaklıdır böcektir, gölette görülür, nedir bu?", a:"Su böceği."},
  {q:"Elektrikle çalışır resim gösterir, salonun ortasında durur, uzaktan kumandası var, nedir bu?", a:"Televizyon."},
  {q:"Kışın karda kayarız üstünde, iki uzun tahtası var, dağda kullanılır, nedir bu?", a:"Kayak."},
  {q:"Küçük ve tüylüdür, peynir sever, kedi ondan korkmaz aslında kaçar, delik açar duvara, nedir bu?", a:"Fare."},
  {q:"Yuvarlaktır zıplamaz, tahta zeminde oynanır elle vurulur, filesi var, nedir bu?", a:"Voleybol topu."},
  {q:"Metal bir kutudur mutfakta durur, yiyecekleri soğuk tutar, kapağı var, nedir bu?", a:"Buzdolabı."},
  {q:"Beyaz renklidir yumuşaktır, kar gibi ama yenir, dondurma değildir pamuk şekeri de değildir, sütten yapılır, nedir bu?", a:"Yoğurt."},
  {q:"Toprağın altında yaşar kör gibidir ama kör değildir, tüneller kazar, kadifemsi tüyü var, nedir bu?", a:"Köstebek."},
  {q:"Kırmızı veya sarıdır çiçektir, dikeni var kokusu güzeldir, aşkın simgesidir, nedir bu?", a:"Gül."},
  {q:"Kağıttan yapılır zarftır, içine mektup konur, pul yapıştırılır, nedir bu?", a:"Zarf."},
  {q:"Sarı renklidir uzundur, kabuğu soyulur içi yumuşaktır, maymunlar sever, nedir bu?", a:"Muz."},
  {q:"Kışın soğuk havada takılır boyuna, yünden örülür uzun ve dardır, nedir bu?", a:"Atkı."},
  {q:"Gökyüzünde uçar motoru var, insan taşır kanatları vardır, havaalanından kalkar, nedir bu?", a:"Uçak."},
  {q:"Yuvarlaktır elde çevrilir, arabanın önündedir yönü belirler, nedir bu?", a:"Direksiyon."},
  {q:"Dört ayaklıdır havlar, kuyruğunu sallar, sadık dosttur evi korur, nedir bu?", a:"Köpek."},
  {q:"Beyaz tüylüdür gıdaklar, yumurta bırakır kümeste, kırmızı ibiği var, nedir bu?", a:"Tavuk."},
  {q:"Sıvıdır tatlıdır arılardan gelir, kahvaltıda ekmeğe sürülür, sarı renklidir, nedir bu?", a:"Bal."},
  {q:"Kağıttan yapılır ince ve uzundur, silgi ucu var yazar, tahtadan da olabilir, nedir bu?", a:"Kurşun kalem."},
  {q:"Kışın camlara buğu yapar, üflenince görünür sonra kaybolur, sıcak nefesten oluşur, nedir bu?", a:"Buğu."},
  {q:"Yeşil renklidir bahçede biter, salatalık gibi ama daha küçüktür, ekşi turşusu olur, nedir bu?", a:"Kornişon."},
  {q:"Dört köşelidir üstü camdır, arabanın önündedir yağmurda silinir, nedir bu?", a:"Ön cam."},
  {q:"Uzun kuyruklu bir hayvandır, ağaçta yaşar fındık toplar, kahverengidir çevik zıplar, nedir bu?", a:"Sincap."},
  {q:"Sabahları uyandırır sesiyle, çiftlikte yaşar kırmızı ibiği var, kanat çırpar öter, nedir bu?", a:"Horoz."},
  {q:"Elde tutulur ısırılır tatlıdır, dondurma değildir waffle de değildir, çikolata kaplıdır dondurma üstündedir, nedir bu?", a:"Külah."},
  {q:"Toprağa gömülür patates gibi ama tatlıdır, turuncu renklidir kabuğu var, nedir bu?", a:"Tatlı patates."},
  {q:"Uzun boyunlu kuştur beyaz tüylü, gölde yüzer zarif hareket eder, boynu S şeklindedir, nedir bu?", a:"Kuğu."},
  {q:"Sıcak havada içilir buzla, şekerli veya şekersiz olur, meyveden sıkılır, nedir bu?", a:"Limonata."},
  {q:"Yuvarlaktır sarı ve kokuludur, dilim dilim kesilir sofrada yenir peynirle, nedir bu?", a:"Kavun dilimi."},
  {q:"Elde taşınır su geçirmez, yağmurda giyilir kapüşonu var, nedir bu?", a:"Yağmurluk."},
  {q:"Sırtında evi olan bir hayvandır, yavaş hareket eder karada da suda da yaşar bazısı, nedir bu?", a:"Kaplumbağa."},
  {q:"Kağıt gibi ince ama yenir, üstünde susam var yuvarlaktır, çayla yenir, nedir bu?", a:"Simit."},
  {q:"Beyaz renklidir bulut gibi ama gökyüzünde değildir, koyunun sırtındadır, kırkılır, nedir bu?", a:"Yün."},
  {q:"Kışın erir yazın buzda tutulur, dondurma yapımında kullanılır soğuktur, nedir bu?", a:"Buz."},
  {q:"Yeşil renklidir toplu şekilde büyür, çorbada kullanılır tanelidir küçüktür, nedir bu?", a:"Bezelye."},
  {q:"Elde tutulur ısırılır, dışı çıtır içi yumuşaktır, ekmek çeşididir, nedir bu?", a:"Baget ekmek."},
  {q:"Uzun ince gagalıdır suda balık avlar, mavi tüylü olanı da vardır, hızla dalar, nedir bu?", a:"Yalıçapkını."},
  {q:"Dört tekerleği var motoru yok, iki kişilik olur çocuklar iter, nedir bu?", a:"Bebek arabası."},
  {q:"Kağıttan katlanır uçmaz ama şekil alır, sanat için yapılır Japon kökenlidir, nedir bu?", a:"Origami."},
  {q:"Sıcak günlerde yenir dondurulur, meyveli veya çikolatalıdır, külahta olur, nedir bu?", a:"Dondurma."},
  {q:"Toprağın üstünde biter, kırmızı küçük tanelidir, reçeli yapılır ekşimsi tatlıdır, nedir bu?", a:"Ahududu."},
  {q:"Uzun ve sivridir kağıda batırılır, mürekkep doludur eskiden kullanılırmış, nedir bu?", a:"Dolma kalem."},
  {q:"Kışın çatıdan sarkar, buzdan oluşur güneşte erir, sivri ucu var, nedir bu?", a:"Buz sarkıtı."},
  {q:"Kırmızı veya yeşildir küçük ve yuvarlaktır, salatada bulunur turşusu da olur, nedir bu?", a:"Zeytin."},
  {q:"Dört ayaklıdır meler, yününden kazak yapılır, kırlarda otlar, nedir bu?", a:"Koyun."}
];
