/* ============ ESPRİLER VERİSİ ============ */
const jokes = [
  { t:"Garson tabağı düşürünce müdür sormuş: 'Ne oldu?' Garson: 'Servis kesildi.'", k:"yemek" },
  { t:"Matematik öğretmeni neden hep yalnızmış? Herkesi bir bilinmeyen sanırmış.", k:"okul" },
  { t:"Hangi anahtar hiçbir kapıyı açmaz? Sol anahtarı.", k:"genel" },
  { t:"Hangi fil uçabilir? Profil.", k:"genel" },
  { t:"Makarna neden uzundur? Kısa olunca spagetti olamadığı için.", k:"yemek" },
  { t:"Kahve neden fincanda içilir? Bardaktan taşmasın diye.", k:"yemek" },
  { t:"Hangi kuş hiç uçamaz? Tavuk.", k:"hayvanlar" },
  { t:"Hangi saat hiç şaşmaz? Duran saat, günde iki kez doğruyu gösterir.", k:"teknoloji" },
  { t:"En akıllı telefon hangisi? Sahibi akıllı olan telefon.", k:"teknoloji" },
  { t:"Öğretmen sormuş: 'Dünya neden döner?' Öğrenci: 'Ben oturunca durur, o yüzden fark etmiyorum' demiş.", k:"okul" },
  { t:"Diyetteyim dedim, arkadaşım 'nasıl gidiyor' diye sordu. 'Kilo dışında her şey harika' dedim.", k:"genel" },
  { t:"Doktora 'iki günde bir baş ağrım tutuyor' dedim. 'Peki hangi günler tutmuyor' dedi, orayı sevdim.", k:"genel" },
  { t:"Patronuma zam istedim. 'Bütçe yok' dedi. Ben de 'motivasyon da yok' dedim, ikimiz de kazandık sanki.", k:"genel" },
  { t:"Arabam çalışmayınca tamirciye götürdüm. 'Ne oldu buna' dedi. 'Bilmiyorum, ben de tamirci değilim ki' dedim.", k:"genel" },
  { t:"Antrenörüm 'her gün 5 kilometre koş' dedi. Ben de her gün koşuyu 5 kilometre erteliyorum.", k:"genel" },
  { t:"Eşim 'sana bir sürpriz hazırladım' dedi. Fatura zarfını açınca gerçekten sürpriz oldum.", k:"iliskiler" },
  { t:"Bir arkadaşım hep geç kalır. Ona 'saat kaçta buluşalım' diye sormayı bıraktım, 'hangi gün buluşalım' diye soruyorum.", k:"iliskiler" },
  { t:"Terapistime 'kendimi hiçbir yere ait hissetmiyorum' dedim. 'Anladım, sırada değilsiniz o zaman' dedi.", k:"genel" },
  { t:"Yeni yılda spor yapacağım dedim, spor salonunun üyelik ücretini görünce kalp atışım hızlandı, ilk hedefe ulaştım sayılır.", k:"genel" },
  { t:"Kaynanam 'yemeğim nasıldı' diye sordu. 'Tuzu tam kararında, tam kavga çıkaracak kadar' dedim.", k:"iliskiler" },
  { t:"Bilgisayarımı formatladım, geçmişimden kurtuldum sandım, yedeklerden hepsi geri geldi.", k:"teknoloji" },
  { t:"Öğretmen 'neden ödevini yapmadın' dedi. 'Yapay zekaya sordum, o da bilmiyormuş' dedim.", k:"okul" },
  { t:"Şoförle tartıştım, 'yaya öncelikli' dedim. 'Hastanede de öncelikli olursun o zaman' dedi.", k:"genel" },
  { t:"Diyetisyenim 'akşam 6'dan sonra yemek yok' dedi. Ben de saatimi 5'te durdurdum, sorun çözüldü.", k:"genel" },
  { t:"Komşum her sabah köpeğini gezdirirken bana selam veriyor, köpek bana, ben köpeğe cevap veriyorum, kimse şikayetçi değil.", k:"hayvanlar" },
  { t:"Ofiste 'toplantı 5 dakika sürecek' dediler, bir saat sonra hâlâ ilk slaytta konuşuyorduk.", k:"genel" },
  { t:"Kedim gece yarısı beni uyandırdı, meğer sadece bana bakıyormuş, sebep bu kadar basit olmamalıydı.", k:"hayvanlar" },
  { t:"Anneme yeni telefonumu gösterdim. 'Kaç para verdin' dedi, cevap vermeden konuyu değiştirdim, en güvenlisi buydu.", k:"iliskiler" },
  { t:"Trafik polisine 'acelem var' dedim. 'Cezanı öderken de acele edersin o zaman' dedi.", k:"genel" },
  { t:"Sınavda 'zaman yetmedi' dedim, öğretmen 'herkese aynı süre verildi' dedi, adalet bazen acımasız oluyor.", k:"okul" },
  { t:"Fitness hocam 'bugün bacak günü' dedi, ertesi gün merdivenleri geri geri indim, tek çözüm buydu.", k:"genel" },
  { t:"Arkadaşım borç istedi, 'param yok' dedim. 'Yalan söylüyorsun, alışverişini gördüm' dedi, yakalandım.", k:"iliskiler" },
  { t:"Bilgisayar dersinde hoca 'kopyala yapıştır yapmayın' dedi, sınıfın yarısı ödevi aynı cümleyle bitirdi.", k:"okul" },
  { t:"Uykusuzluktan şikayet ettim doktoruma, 'telefonu yatağa götürme' dedi, en zor tavsiyeyi en kolay şekilde verdi.", k:"teknoloji" },
  { t:"Yeni bir dil öğreneceğim dedim, uygulamayı indirdim, üç gün sonra bildirimleri kapattım, dil hâlâ öğrenilmedi.", k:"genel" },
  { t:"Toplu taşımada koltuğumu bir yaşlı teyzeye verdim, teşekkür yerine 'gençsin, ayakta dur' dedi, ders aldım.", k:"genel" },
  { t:"Yeni işe başladım, ilk gün herkesin adını unuttum, ikinci gün kendi adımı unutmadığıma sevindim.", k:"genel" },
  { t:"Balık tutmaya gittim, üç saat bekledim, tek yakaladığım güneş yanığı oldu.", k:"hayvanlar" },
  { t:"Doktor 'tuzu azaltın' dedi. Ben de tuzluğu masadan kaldırdım, sorunu kökten çözdüm.", k:"yemek" },
  { t:"Kardeşim 'arabamı sen mi çizdin' dedi. 'Hayır ama tamircinin numarasını biliyorum' dedim.", k:"iliskiler" },
  { t:"Yoga hocam 'zihnini boşalt' dedi, ben de market listemi unuttum, tam istediği gibi oldu.", k:"genel" },
  { t:"Bir web sitesine giriş yapamadım, şifremi sıfırladım, yeni şifre eskisiyle aynı çıktı, sistem beni tanıdı.", k:"teknoloji" },
  { t:"Halı sahada gol attım, kimse kutlamadı çünkü kendi kalemize atmışım.", k:"genel" },
  { t:"Aşçı okuluna gittim, ilk dersimde suyu yakmayı başardım, hoca bile şaşırdı.", k:"yemek" },
  { t:"Köpeğim topu getir oyununu öğrendi ama sadece topu getiriyor, geri vermiyor, pazarlık gücü bende değil.", k:"hayvanlar" },
  { t:"Sunumumu hazırladım, sunum sırasında projektör bozuldu, en güzel slaytımı kimse göremedi, hayat bu.", k:"genel" },
  { t:"Kuaförüme 'saçımı çok kısa kesme' dedim, aynaya baktığımda okul fotoğrafı çektirecekmişim gibi hissettim.", k:"genel" },
  { t:"Arkadaşıma borç para verdim, 'ne zaman ödersin' diye sormadım, cevabı zaten biliyordum.", k:"iliskiler" },
  { t:"Yeni telefonumun pili bir günde bitiyor, eski telefonuma özlem duymaya başladım, o hiç şarj istemezdi sanki.", k:"teknoloji" },
  { t:"Spor salonunda ilk gün ağırlık kaldırdım, ikinci gün merdiven bile kaldıramadım, kaslarım intikam aldı.", k:"genel" },
  { t:"Balkonumda domates yetiştirmeye çalıştım, tek yetişen şey komşunun şikayeti oldu.", k:"yemek" },
  { t:"Öğretmenim 'sınavdan önce dua et' dedi, dua ettim ama soruları da çalışmam gerekiyormuş meğer.", k:"okul" },
  { t:"Yeni yıl kararımı hiç değiştirmiyorum, her yıl aynı kararı veriyorum, tutarlılık bu olsa gerek.", k:"genel" },
  { t:"Kedime yeni oyuncak aldım, o da kutuyla oynadı, para yerinde durdu aslında.", k:"hayvanlar" },
  { t:"Arabamın yakıt göstergesi kırmızıya döndü, ben de radyoyu kıstım, sanki yakıt tasarrufu olacakmış gibi.", k:"genel" },
  { t:"Diyet yaparken market alışverişine çıktım, aç karnına gitmenin bedelini üç poşet cipsle ödedim.", k:"yemek" },
  { t:"Kızıma 'neden okulu sevmiyorsun' dedim. 'Herkes benden bir şey istiyor, öğretmen ödev, arkadaşım kalem, sen not' dedi.", k:"okul" },
  { t:"Muhasebeciye 'param nereye gitti' dedim. 'Tablo yaptım ama üzülürsün' dedi, üzülmemeyi seçtim, tabloyu görmedim.", k:"genel" },
  { t:"Yeni yıl için 'erken yatacağım' dedim, telefonumu kontrol ederken sabah oldu, plan hâlâ geçerli sayılır.", k:"genel" },
  { t:"Kuzenim evlilik teklifini nasıl yapacağını sordu, 'doğal ol' dedim, sonra o kadar doğal oldu ki kız 'ne oldu' diye sordu.", k:"iliskiler" },
  { t:"Doktorum 'stresten uzak durun' dedi, sonra faturayı gösterdi, tavsiyesiyle çelişen tek an oydu.", k:"genel" },
  { t:"Telefonuma 'şarj %1' yazınca hayatım film sahnesine döndü, hangi tel neye gidiyor bulmaya çalıştım.", k:"teknoloji" },
  { t:"Wi-Fi şifresini unuttum, ailemle üç gün konuşmak zorunda kaldım, sonra internet kutusunun altında yazdığını gördüm.", k:"teknoloji" },
  { t:"Yapay zekaya 'beni motive et' dedim, 'yapabilirsin' dedi, ben de 'neyi' diye sordum, cevap alamadım.", k:"teknoloji" },
  { t:"Akıllı saatim 'kalk yürü' diye titredi, ben de saati çıkarıp masaya bıraktım, yürüyen o oldu artık.", k:"teknoloji" },
  { t:"Yeni oyun konsolu aldım, kutusunu açmak internetten indirmekten daha uzun sürdü.", k:"teknoloji" },
  { t:"Sosyal medyada 'bir yıl önce bugün' hatırlatması geldi, keşke hatırlatmasa dedim ama artık geç.", k:"teknoloji" },
  { t:"Telefonun otomatik düzeltmesi 'seni seviyorum' yazmam gerekirken 'seni seveyim' yazdı, ilişki orada bitti sayılır.", k:"teknoloji" },
  { t:"Bilgisayarıma virüs bulaştı, tarama yaptırdım, sonuç: bilgisayar benden daha temiz çıktı.", k:"teknoloji" },
  { t:"E-postama 'acil' başlıklı bir mail geldi, iki hafta sonra açtım, gerçekten acilmiş ama artık geçmişti.", k:"teknoloji" },
  { t:"Yapay zeka asistanıma hava durumunu sordum, 'dışarı çık bakarsın' dedi, teknoloji bazen tembelliği de öğreniyor.", k:"teknoloji" },
  { t:"Öğretmen 'telefonları kapatın' dedi, herkes sessize aldı, kapatma ile sessize alma arasındaki fark asla anlaşılmadı.", k:"okul" },
  { t:"Sınıfta 'kim yapmadıysa elini kaldırsın' dedi hoca, kimse kaldırmadı ama herkes birbirine baktı.", k:"okul" },
  { t:"Ödev teslim tarihini bir gün önce hatırladım, o gece uyumadım, sabah yine geç kaldım.", k:"okul" },
  { t:"Sınavda 'boş bırakmayın' yazısını okuyunca adımı bile boş bıraktım, panik böyle bir şey.", k:"okul" },
  { t:"Grup ödevinde bir kişi çalışır, dördü WhatsApp grubunda 'harikasın' emojisi atar, denge böyle sağlanır.", k:"okul" },
  { t:"Öğretmenim 'bu konudan sınavda soru çıkacak' dedi, tam o konuyu çalışmadığım gün çıktı.", k:"okul" },
  { t:"Final haftasında uyku düzenim bozuldu, kahve düzenim düzeldi, biri diğerini dengeledi sanırım.", k:"okul" },
  { t:"Rehber öğretmen 'gelecekte ne olmak istiyorsun' dedi, 'şu an hayatta kalmak istiyorum' dedim, yeterliydi.", k:"okul" },
  { t:"Okulda kantin sırası maratondan uzundu, teneffüs bitti ben daha kasaya varamadım.", k:"okul" },
  { t:"Öğretmen 'telefonunuzu masaya koyun' dedi, ben de eski model çalar saatimi koydum, kural bozulmadı.", k:"okul" },
  { t:"Kantinde para üstü istedim, 'kalsın hocam' dedi kasiyer, sadece iki lira olmasına rağmen hayatımın en cömert anıydı.", k:"okul" },
  { t:"Anneme yemek beğenmediğimi söylemek yerine 'karnım tok' dedim, tabağı sıyırdığımı görünce yakalandım.", k:"yemek" },
  { t:"Fırında kek yaptım, tarifte 'orta ateş' yazıyordu, benim ocakta orta diye bir ayar yokmuş meğer.", k:"yemek" },
  { t:"Restoranda garson 'başka bir şey ister miydiniz' dedi, 'hesap gelmesin' dedim, gülümseyerek uzaklaştı.", k:"yemek" },
  { t:"Diyet çorbası içtim, doymadım, üstüne iki dilim ekmek yedim, çorba boşuna içilmiş oldu.", k:"yemek" },
  { t:"Yeni tarif denedim, 'kolay' yazıyordu ama mutfakta üç saat geçirdim, kolaylığın tanımı değişmiş olmalı.", k:"yemek" },
  { t:"Marketten 'indirimde' yazan ürünü aldım, kasada normal fiyattan çıktı, indirim sadece rafta kalmış.", k:"yemek" },
  { t:"Pizza siparişi verdim, '30 dakikada gelir' dediler, bir saat sonra geldi, soğumuş ama sabrım da tükenmişti.", k:"yemek" },
  { t:"Salçayı kavurmadan yemek yapmak Türk mutfağında affedilmez bir suçtur, annem böyle söyledi, itiraz etmedim.", k:"yemek" },
  { t:"Yemek yaparken tarifi takip ettim, sonuç anneminkine hiç benzemedi, sır tarifte değil ellerdeymiş.", k:"yemek" },
  { t:"Mutfakta un serpiştirirken kendim de una bulandım, sonuçta hamur olan ben oldum yemek değil.", k:"yemek" },
  { t:"Kedim laptopumun üstüne oturdu, toplantıya böyle katıldı, patronum ondan daha ilgiliydi.", k:"hayvanlar" },
  { t:"Köpeğimi veterinere götürdüm, 'sağlıklı' dedi doktor, köpeğim de sanki anlamış gibi kuyruk salladı.", k:"hayvanlar" },
  { t:"Papağanım her sabah 'günaydın' diyor ama akşam da aynı şeyi söylüyor, saat kavramı yok galiba.", k:"hayvanlar" },
  { t:"Balığıma yeni akvaryum aldım, o hâlâ eski köşesinde duruyor, değişime açık değilmiş.", k:"hayvanlar" },
  { t:"Kaplumbağamın adını koydum ama üç yıldır cevap vermiyor, sabır konusunda benden iyi olmalı.", k:"hayvanlar" },
  { t:"Köpeğim postacıyı görünce havlıyor, ben görünce sevinçle zıplıyor, ikisi de aynı kapıdan giriyor oysa.", k:"hayvanlar" },
  { t:"Kedimi kucağıma aldım, beş saniye sonra indi, sevginin süresi bazen çok kısa oluyor.", k:"hayvanlar" },
  { t:"Akvaryumdaki balık camdan bana bakıyor, ben de ona bakıyorum, ikimiz de birbirimizi anlamıyoruz ama huzurluyuz.", k:"hayvanlar" },
  { t:"Hamsterımın koşu tekerleği gece boyu döndü, sabah baktım hâlâ aynı yerde, verimlilik kavramı ona yabancı.", k:"hayvanlar" },
  { t:"Köpeğime 'otur' dedim oturdu, 'yat' dedim yattı, 'bulaşıkları yıka' dedim beni izledi, sınır orada başlıyor.", k:"hayvanlar" },
  { t:"Eşimle alışverişe çıktık, o liste yaptı ben unuttum, market arabası dolu ama listedeki hiçbir şey yok.", k:"iliskiler" },
  { t:"Kız arkadaşım 'bir şey yok' dedi, ben inandım, iki saat sonra 'bir şey yok'un aslında çok şey olduğunu öğrendim.", k:"iliskiler" },
  { t:"Anneannem 'evlen artık' dedi, ben 'kiminle' dedim, o da 'bulursun' dedi, tavsiye tam olarak bu kadardı.", k:"iliskiler" },
  { t:"Arkadaşım doğum günümü unuttu, ben de onunkini unutmuş gibi yaptım, adalet böyle sağlandı.", k:"iliskiler" },
  { t:"Sevgilim 'ne düşünüyorsun' diye sordu, 'hiçbir şey' dedim, kafamda otuz farklı senaryo dönerken.", k:"iliskiler" },
  { t:"Kardeşimle kavga ettik, sebep neydi hatırlamıyoruz ama küslük hâlâ devam ediyor, prensip meselesi bu.", k:"iliskiler" },
  { t:"Babam 'benim zamanımda' diye başlayınca herkes telefonuna gömülür, hikaye yine de anlatılır.", k:"iliskiler" },
  { t:"Arkadaşıma sır verdim, 'kimseye söyleme' dedim, ertesi gün herkes biliyordu, sır bende kalmıştı ama telefonda değil.", k:"iliskiler" },
  { t:"Eşim alışveriş listesi yazdı, ben markette listeyi evde unuttuğumu fark ettim, hafızama güvenmek büyük hataydı.", k:"iliskiler" },
  { t:"Yeni komşum kapımı çaldı 'tuz ödünç alabilir miyim' dedi, üç yıldır iade etmedi, komşuluk böyle başladı.", k:"genel" },
  { t:"Otobüs durağında bekledim, otobüs tam ben telefonuma baktığım an geldi ve geçti, senkronizasyon mükemmeldi.", k:"genel" },
  { t:"Yeni yıl listeme 'daha az plan yap' yazdım, sonra listedeki diğer on maddeyi de yapmadım, tutarlıydım en azından.", k:"genel" },
  { t:"Markete 'sadece ekmek alacağım' diye girdim, üç poşetle çıktım, ekmek en son hatırladığım şeydi.", k:"genel" },
  { t:"Sabah alarmı beş kere erteledim, sonunda kalktığımda alarm kurma amacımı sorguladım.", k:"genel" },
  { t:"Trafik ışığında bekliyordum, yeşil yanınca herkes korna çaldı, ben hâlâ telefonumla meşguldüm, klasik.", k:"genel" },
  { t:"Kilo vermek için merdiven kullanmaya başladım, asansör bozulunca mecburen sağlıklı oldum.", k:"genel" },
  { t:"Hava durumu 'güneşli' dedi, şemsiyesiz çıktım, yağmur da tam üstüme boşaldı, meteoroloji ile aramda husumet var.", k:"genel" },
  { t:"Uyandığımda 'bugün üretken olacağım' dedim, öğlene kadar telefonda sosyal medyayı kaydırdım, plan böyle bozuldu.", k:"genel" },
  { t:"Cüzdanımı ararken elimde tutuyordum, on dakika sonra fark ettim, panik akıl yürütmeyi durduruyor.", k:"genel" },
  { t:"Terapistime 'her şeyi erteliyorum' dedim, 'bunu konuşalım' dedi, 'yarın konuşalım' dedim, kendimi ele verdim.", k:"genel" },
  { t:"Yeni yıl kararı olarak 'daha çok kitap okuyacağım' dedim, kitabı aldım, yastığın altında güzel duruyor.", k:"genel" },
  { t:"Kuru temizlemeciye ceketi bıraktım, 'üç gün sürer' dedi, on gün sonra hâlâ gitmedim almaya.", k:"genel" },
  { t:"Sabah spor yapacağım dedim, spor kıyafetlerini giydim, koltukta o kıyafetlerle uyuyakaldım, niyet önemliydi.", k:"genel" },
  { t:"Bulaşık makinesi 'temiz' ışığı yaktı ama tabaklar hâlâ yağlıydı, teknoloji bazen bize güvenmemizi istiyor sadece.", k:"teknoloji" },
  { t:"Telefonumu düşürünce ekranı çatladı, tamirci 'yeni telefon almak daha ucuz' dedi, teselli olmadı.", k:"teknoloji" },
  { t:"Uygulama güncellemesi yaptım, arayüz değişti, hiçbir düğmeyi bulamadım, ilerleme böyle bir şeymiş demek.", k:"teknoloji" },
  { t:"Akıllı ev sistemim 'ışıkları kapat' dedim, müzik çaları açtı, ev bazen kendi kararlarını veriyor.", k:"teknoloji" },
  { t:"Şarj kablosu her seferinde ters geliyor, üç denemede doğru tarafı buluyorum, evrenin bir kanunu bu.", k:"teknoloji" },
  { t:"Yazılım güncellemesini 'daha sonra hatırlat' dedim, altı ay sonra hâlâ hatırlatıyor, sadakat böyle bir şey.", k:"teknoloji" },
  { t:"Yapay zekaya şiir yazdırdım, güzeldi ama imzayı kendi adıma attım, sanat böyle işliyor bazen.", k:"teknoloji" },
  { t:"Klavyemde bir tuş bozuldu, tam da en çok kullandığım harf, evren beni test ediyor sanki.", k:"teknoloji" },
  { t:"Ekran koruyucu balık tankı gösteriyor, gerçek balığım olsa bu kadar ilgi görmezdi.", k:"teknoloji" },
  { t:"Bilgisayarımın fanı uçak kalkışı gibi ses çıkarıyor, sadece bir sekme açtım ama sistem panikledi.", k:"teknoloji" },
  { t:"Öğretmen 'telefonlarınızı toplayın' dedi, kutuya koyarken herkesin eli titredi, ayrılık böyle acı verir.", k:"okul" },
  { t:"Beden dersinde 'koşun' dedi hoca, herkes yürüdü ama hızlı yürüdü, koşu bu şekilde tanımlandı.", k:"okul" },
  { t:"Sınav kağıdını teslim ederken 'emin misin' dedi hoca, 'hayır ama artık geç' dedim.", k:"okul" },
  { t:"Tarih dersinde tarihleri ezberledim, sınavda hepsini karıştırdım, tarih bazen kendini tekrar etmiyor.", k:"okul" },
  { t:"Öğretmenim 'sessiz okuyun' dedi, sınıf o kadar sessizdi ki karnımın sesi duyuldu, mahcup oldum.", k:"okul" },
  { t:"Proje sunumunda slaytları karıştırdım, konuyu değiştirmiş gibi oldum ama kimse fark etmedi sanırım.", k:"okul" },
  { t:"Kimya dersinde deney yaptık, benim tüpten sadece duman çıktı, notum da duman gibi uçtu.", k:"okul" },
  { t:"Rehberlik saatinde 'stresle nasıl başa çıkıyorsunuz' diye sordular, 'stres bende yok, panik var' dedim.", k:"okul" },
  { t:"Yeni dönem başladı, defterlerim tertemiz, bir hafta sonra hepsi karalama defterine döndü.", k:"okul" },
  { t:"Fen dersinde 'sorularınız var mı' dedi hoca, benim tüm dersle ilgili bir sorum vardı ama soramadım.", k:"okul" },
  { t:"Yemek tarifinde 'bir tutam tuz' yazıyordu, benim tutamım biraz cömertmiş, yemek deniz suyu gibi oldu.", k:"yemek" },
  { t:"Restoranda menüyü on dakika inceledim, sonunda hep sipariş ettiğim şeyi söyledim, özgür irade sınırlıymış.", k:"yemek" },
  { t:"Yeni bir kahve makinesi aldım, ilk kahvem yanık kokuyordu, makine de benim gibi tecrübesizmiş.", k:"yemek" },
  { t:"Salata yaptım, üstüne o kadar sos döktüm ki artık salata değil sos kasesi oldu.", k:"yemek" },
  { t:"Fırından çıkan kurabiyeler yanmış görünüyordu, 'rustik' dedim, kimse itiraz etmedi.", k:"yemek" },
  { t:"Baharat dolabımda on çeşit baharat var, hepsinin tadı aynı geliyor bana, damak zevkim gelişmemiş sanırım.", k:"yemek" },
  { t:"Yeni diyete başladım, ilk gün başarılıydım, ikinci gün dolapta çikolata aradım, kendimi tanıyorum artık.", k:"yemek" },
  { t:"Pilavı tam kıvamında yapmak için annemi aradım, tarifi anlattı ama sonuç yine farklı çıktı, sır ellerdeymiş demek.", k:"yemek" },
  { t:"Yemek siparişi verirken 'acı olsun' dedim, gelen yemek dilimi yaktı, cesaretimin bedeli buydu.", k:"yemek" },
  { t:"Buzdolabını açtım, 'yiyecek bir şey yok' dedim, dolu bir dolaba bakarken bu cümleyi kurmak insanlığın gizemi.", k:"yemek" },
  { t:"Papağanım komşunun adını öğrendi, artık sabah sabah onu çağırıyor, komşuluk ilişkileri böyle gelişiyor.", k:"hayvanlar" },
  { t:"Köpeğim aynadaki kendine havlıyor, üç yıldır bu böyle, hâlâ tanışamadılar.", k:"hayvanlar" },
  { t:"Kedimi banyoya soktum, sonrasında evi bir hafta boyunca gördüğüm en dramatik bakışlarla dolaştı.", k:"hayvanlar" },
  { t:"Balığımı yeni bir kaseye taşıdım, o hâlâ eski kasenin olduğu yere doğru yüzüyor, alışkanlık güçlü bir şey.", k:"hayvanlar" },
  { t:"Köpeğimle yürüyüşe çıktım, o beni gezdirdi aslında, kim kimin sahibi belli değil artık.", k:"hayvanlar" },
  { t:"Kuşuma ayna koydum, kendine aşık oldu sandım, meğer sadece yansımasıyla dans ediyormuş.", k:"hayvanlar" },
  { t:"Kedim gece yarısı koşuşturmaya başladı, komşular gürültüden şikayet etti, o hâlâ atletik kariyerine devam ediyor.", k:"hayvanlar" },
  { t:"Köpeğime yeni mama aldım, koklayıp yemedi, eski mamayı geri getirince yedi, sadakat bu.", k:"hayvanlar" },
  { t:"Annemle telefon konuşması bir saat sürdü, konuşulan konu 'nasılsın' idi, detaylara böyle giriliyor.", k:"iliskiler" },
  { t:"Eşimle film seçerken bir saat tartıştık, sonunda ikimizin de sevmediği bir film izledik, uzlaşma buydu.", k:"iliskiler" },
  { t:"Arkadaşım 'sana güveniyorum' dedi, sırrını anlattı, ben de en yakın arkadaşıma anlattım, güven zinciri böyle işliyor.", k:"iliskiler" },
  { t:"Kardeşimle miras konuşmasına daha yıllar var ama şimdiden kim hangi eşyayı alacak diye tartışıyoruz.", k:"iliskiler" },
  { t:"Sevgilim 'seni hiç kıskanmıyorum' dedi, telefonuma bakarken bunu söylemesi ilginçti.", k:"iliskiler" },
  { t:"Babaannem her ziyarette 'kilo almışsın' der, sevgi dili böyle farklı, itiraz etmiyorum artık.", k:"iliskiler" },
  { t:"Arkadaşımla dargın olduğumuz üç gün boyunca birbirimizin hikayelerini izledik, dargınlık dijital çağda böyle.", k:"iliskiler" },
  { t:"Eşim 'hiçbir şey istemiyorum' dedi doğum günü için, hediyeyi beğenmeyince gerçek listeyi öğrendim.", k:"iliskiler" },
  { t:"Otobüs beklerken yağmur başladı, şemsiyem çantada değil evdeydi, evren mizah anlayışını gösteriyor bazen.", k:"genel" },
  { t:"Sabah kahvemi masaya koydum, unuttum, akşam soğuk kahveyi buldum, unutkanlık kahveyi de bekletiyormuş.", k:"genel" },
  { t:"Yürüyüşe çıktım, telefonum düşürüldü, eğilip aldım, adım sayacım hiç fark etmedi bu maceramı.", k:"genel" },
  { t:"Market alışverişinde indirim kartımı evde unuttum, kasada bunu fark ettim, hayatın küçük cezaları böyle.", k:"genel" },
  { t:"Yeni yıl gecesi 'bu sene daha erken yatacağım' dedim, saat 3'te bunu söylerken bile.", k:"genel" },
  { t:"Uykuya dalamayınca koyun saydım, elli ikide vazgeçtim, koyunlar da benim gibi yorulmuş olmalı.", k:"genel" },
  { t:"Trafik sıkışıklığında müzik açtım, radyo tam trafik haberini verirken kapandı, teknoloji şaka yapıyor bazen.", k:"genel" },
  { t:"Bir hafta boyunca erken kalkacağıma dair kendime söz verdim, üçüncü gün alarmı fırlatıp attım.", k:"genel" },
  { t:"Kütüphaneye kitap iade etmeye gittim, geciken günler için ceza ödedim, okumak bu kadar pahalıymış meğer.", k:"genel" },
  { t:"Yeni ayakkabı aldım, ilk gün topuğumu vurdu, güzellik acı ile gelir derler doğruymuş.", k:"genel" },
  { t:"Kilo kontrolü için terazi aldım, her tarttığımda farklı sonuç veriyor, terazi de kararsız görünüyor.", k:"genel" },
  { t:"Kahve fincanımı iş yerinde unuttum, eve elim boş gitti ama kahve hasretim tam.", k:"genel" },
  { t:"Cumartesi sabahı erken kalkıp temizlik yapacağıma karar verdim, öğlen uyandığımda karar hâlâ orada duruyordu.", k:"genel" },
  { t:"Yağmurlu bir günde şemsiyeyi unuttum ama güneş gözlüğümü yanımda taşıyordum, önceliklerim ilginç.", k:"genel" },
  { t:"Yeni telefonumu kutusundan çıkarırken eski telefonuma bir bakış attım, veda anları böyle acı verir.", k:"teknoloji" },
  { t:"Bilgisayar oyunu oynarken elektrik kesildi, kaydetmediğim ilerleme uçtu, hayat böyle dersler veriyor.", k:"teknoloji" },
  { t:"Yeni klavye aldım, tuşların sesi o kadar yüksek ki gece yazı yazmak suç işlemek gibi hissettiriyor.", k:"teknoloji" },
  { t:"Telefonuma 'güncelleme mevcut' yazısı üç aydır çıkıyor, 'daha sonra' dedim, o güven hâlâ devam ediyor.", k:"teknoloji" },
  { t:"Sınıfta grup projesi paylaştık, herkes 'sen yaparsın zaten' dedi, iltifat mı yük mü anlayamadım.", k:"okul" },
  { t:"Matematik sınavında formülü ezberledim ama neye yarıyor bilmiyordum, o gün notumla birlikte bu da ortaya çıktı.", k:"okul" },
  { t:"Sınav sonuçlarını öğretmen dağıtırken herkesin yüzü aynı anda değişti, o sahne bir belgesele konu olabilir.", k:"okul" },
  { t:"Kütüphanede ders çalışacağım dedim, bir saat sonra baktım telefonda video izliyorum, plan değişmişti.", k:"okul" },
  { t:"Yemek tarifini takip ederken bir adımı atladım, sonuç beklenmedik ama yenmeyecek kadar da kötü değildi.", k:"yemek" },
  { t:"Kahvaltıda yumurta pişirirken telefonla ilgilendim, yumurta kayaya döndü, dikkatimi test etti mutfak.", k:"yemek" },
  { t:"Alışveriş listesine 'sebze' yazdım, markette hangi sebze olduğunu hatırlamadım, genel kavramlar işe yaramadı.", k:"yemek" },
  { t:"Yeni bir restorana gittik, menü İngilizce'ydi, ne sipariş ettiğimi anlamadan yedim, macera böyle başlar.", k:"yemek" },
  { t:"Kedim mutfak tezgahına çıktı, ona 'in' dedim, beni izleyip devam etti, otorite tanımıyor bu ev.", k:"hayvanlar" },
  { t:"Köpeğimi parka götürdüm, o benden çok başka köpeklerle ilgilendi, sosyal hayatı benimkinden zengin.", k:"hayvanlar" },
  { t:"Balık akvaryumunu temizlerken balık bana küskün baktı, temizlik bile hoşuna gitmedi.", k:"hayvanlar" },
  { t:"Eşimle tatil planı yaparken o dağı ben denizi istedi, sonunda ikisi de olmayan bir yere gittik.", k:"iliskiler" },
  { t:"Arkadaşım 'sadece beş dakika gecikirim' dedi, bir saat sonra geldi, matematik ilişkilerde farklı işliyor.", k:"iliskiler" },
  { t:"Ailemle akşam yemeğinde herkes telefonuna baktı, sohbet WhatsApp gruplarında devam etti masanın altında.", k:"iliskiler" },
  { t:"Otobüs durağında birini bekliyordum, o da beni bekliyordu ama farklı duraklarda, iletişim böyle koptu.", k:"genel" },
  { t:"Yeni bir hobi edineceğim dedim, ekipmanı aldım, iki hafta kullandım, dolapta yeni bir anı oldu.", k:"genel" },
  { t:"Sabah aynaya baktım, dünkü halimi gördüm, değişim yavaş oluyormuş meğer.", k:"genel" },
  { t:"Toplantıda 'kısa tutalım' dediler, iki saat sürdü, kısa kelimesinin tanımı toplantı odalarında farklı.", k:"genel" },
  { t:"Yeni bir spor dalına başladım, ilk derste kendimden çok hocayı yordum sorularımla.", k:"genel" },
  { t:"Evi toplarken bir kutu buldum, içinde ne olduğunu hatırlamadım, açtım, gelecekteki ben geçmişteki bene teşekkür etti.", k:"genel" },
  { t:"Trafik lambası kırmızıya döndüğünde tam ben geçtim, arkadaki araçlar bekledi, zamanlama sanat gibi bir şey.", k:"genel" },
  { t:"Kışlık montumu dolaptan çıkardım, hava aniden ısındı, doğa da benimle dalga geçiyor sanki.", k:"genel" },
  { t:"Yeni yıl için spor salonuna üye oldum, ocak ayında kalabalıktı, şubatta salon yine bana kaldı.", k:"genel" },
  { t:"Bahçedeki çiçekleri suladım, komşunun çiçekleri de bizim tarafa uzanmış, komşuluk suyla da gelişiyor.", k:"genel" },
  { t:"Yeni bir defter aldım, ilk sayfasını en güzel yazımla yazdım, ikinci sayfa çirkin karalamalarla doldu.", k:"genel" },
  { t:"Otobüste uyuyakaldım, durağımı geçtim, uyanınca hangi şehirde olduğumu sorguladım.", k:"genel" },
  { t:"Kahve makinesi bozuldu, elle kahve yapmaya çalıştım, sonuç kahveden çok toprak suyu gibiydi.", k:"yemek" },
  { t:"Yemek pişirirken tuzu iki kere koydum, unutkanlık ile tuzluluk el ele gidiyor mutfakta.", k:"yemek" },
  { t:"Dondurma aldım, eve gelene kadar erimişti, sıcak havayla yarışı ben kaybettim.", k:"yemek" },
  { t:"Kahvaltı masasında herkes telefonunu kontrol ediyordu, sadece ekmek kırıntıları sohbet ediyordu masada.", k:"iliskiler" },
  { t:"Köpeğim çamura battı, eve geldiğinde önce beni öptü sonra halıyı kirletti, öncelik sırası netti.", k:"hayvanlar" },
  { t:"Kedime yeni tasma aldım, üç saniye taktı sonra ısırıp çıkardı, moda anlayışı sınırlı.", k:"hayvanlar" },
  { t:"Okulda münazara yarışmasına katıldım, kendi görüşümü savunurken bile kendimi ikna edemedim.", k:"okul" },
  { t:"Fen bilgisi hocası 'deney yapın' dedi, benim deneyim laboratuvarı biraz dumanlandırdı, bilim böyle ilerliyor.", k:"okul" },
  { t:"Yeni telefon aldım, eski telefonumu satmaya çalıştım, alıcı 'ekranı çizik' dedi, hafızalarım da çizikliymiş demek.", k:"teknoloji" },
  { t:"Akıllı hoparlörüme şarkı söylemesini istedim, yanlış anlayıp alarm kurdu, müzisyenlik yeteneği yok.", k:"teknoloji" },
  { t:"İnternetten sipariş verdim, kargo takibinde 'yolda' yazıyor üç haftadır, o yol epey uzunmuş.", k:"teknoloji" },
  { t:"Yapay zekaya kod yazdırdım, çalıştı ama neden çalıştığını ikimiz de bilmiyoruz.", k:"teknoloji" },
  { t:"Öğretmenim ödevleri online sisteme yükleyin dedi, sistem çöktü, teknoloji bazen mazeret üretiyor bize.", k:"okul" },
  { t:"Sınıfta proje sunarken slaytım açılmadı, doğaçlama yaptım, hoca 'yaratıcı' dedi, aslında çaresizdim.", k:"okul" },
  { t:"Coğrafya dersinde harita çizdim, öğretmen 'bu hangi ülke' diye sordu, ben de 'hayal ürünü' dedim.", k:"okul" },
  { t:"Yemekhanede sıra beklerken karnım guruldadı, herkes döndü baktı, mahremiyet diye bir şey kalmadı.", k:"yemek" },
  { t:"Yeni bir tarif denedim, sonucu fotoğrafladım ama tadına bakmadan önce, sosyal medya öncelik almış artık.", k:"yemek" },
  { t:"Fırında pizza yaparken hamuru inceltmeyi unuttum, sonuç ekmek mi pizza mı belli olmadı.", k:"yemek" },
  { t:"Kahve içmeden konuşmuyorum dedim, sabah biri bana bir şey sordu, cevap yerine kahveye işaret ettim.", k:"yemek" },
  { t:"Köpeğim yeni oyuncağını gömdü, sonra nereye gömdüğünü unuttu, hafıza konusunda ben de aynıyım aslında.", k:"hayvanlar" },
  { t:"Kediler gece koşuşturma saatinde en enerjik hallerini gösteriyor, gündüz uyuyup gücü biriktiriyorlar sanırım.", k:"hayvanlar" },
  { t:"Papağanıma yeni kelime öğretmeye çalıştım, o hâlâ eski kelimesinde ısrarcı, değişime kapalı.", k:"hayvanlar" },
  { t:"Arkadaşımla buluşma saatini konuştuk, o 'akşamüstü' dedi, ben 'akşam' anladım, buluşma iki saat gecikti.", k:"iliskiler" },
  { t:"Ailecek fotoğraf çektirdik, herkes gözlerini kapattığı an yakalandı, o kare albümün baş köşesinde.", k:"iliskiler" },
  { t:"Kardeşimle çocukluk anılarını konuştuk, ikimiz de aynı olayı farklı hatırlıyoruz, hafıza subjektif bir şeymiş.", k:"iliskiler" },
  { t:"Otobüste yer verdim, karşılığında 'gençsin dinlenirsin' dediler, iyilik bazen böyle geri döner.", k:"genel" },
  { t:"Yeni bir spor ayakkabı aldım, koşmaya başladım, iki gün sonra ayakkabı bende koştu bir köşede duruyor.", k:"genel" },
  { t:"Sabah erkenden kalkıp güne başlamak istedim, alarm çaldı, saat kavramını yeniden düşündüm.", k:"genel" },
  { t:"Evde düzen yapacağım dedim, bir kutuyu açtım, içinden çıkan eski fotoğraflara dalıp günü orada geçirdim.", k:"genel" },
  { t:"Hafta sonu tatil planı yaptım, hava durumuna bakmadım, yağmur planı da benimle birlikte ıslattı.", k:"genel" },
  { t:"Yeni bir kitap almaya karar verdim, kitapçıda üç saat gezdim, elimde kahve fincanıyla çıktım.", k:"genel" },
  { t:"Uzun zamandır ertelediğim işi bugün yapacağım dedim, bu cümleyi kurmak bile bir haftamı aldı.", k:"genel" },
  { t:"Kilo almamak için asansör yerine merdiven kullandım, sonra iki kat aşağı indiğimi fark ettim, yön de sınav gibiymiş.", k:"genel" },
  { t:"Yeni yıl kararlarımı yazdığım kağıt hâlâ çekmecede duruyor, kararlar orada yaşıyor sadece.", k:"genel" },
  { t:"Öğretmenim 'kimin sorusu var' dedi, benim yüz sorum vardı ama hiçbiri konuyla alakalı değildi.", k:"okul" },
  { t:"Sınav kağıdıma adımı yazmayı unuttum, hoca 'bu kimin' dedi, kimliğimi kaybettiğimi o an anladım.", k:"okul" },
  { t:"Ödevimi köpeğim yedi demek istedim ama köpeğim yok, bahane bile üretemedim.", k:"okul" },
  { t:"Beden dersinde ip atlarken kendi ayağıma takıldım, spor yeteneğim böyle netleşti.", k:"okul" },
  { t:"Müzik dersinde flüt çaldık, benim çıkardığım ses kuş bile kaçırdı camdan.", k:"okul" },
  { t:"Resim dersinde 'hayal gücünüzü kullanın' dedi hoca, benim hayal gücüm bir çizgiyle sınırlıydı.", k:"okul" },
  { t:"Öğretmen 'kimse kopya çekmesin' dedi, herkes kalemini masadan kaldırdı sanki suçluymuş gibi.", k:"okul" },
  { t:"Bilgisayarımı yeniden başlattım, sorun geçti, mühendislik bazen kapat aç kadar basit.", k:"teknoloji" },
  { t:"Telefonuma yeni bir uygulama indirdim, izinleri okumadan kabul ettim, kameramı bile ona verdim galiba.", k:"teknoloji" },
  { t:"Akıllı saatim adım sayısını yanlış saydı, ben otururken bile adım atmışım gibi gösterdi, hareketli bir hayatım varmış meğer.", k:"teknoloji" },
  { t:"Bulut sistemine yükledim dosyaları, 'her yerden erişebilirsin' dediler, şifreyi unutunca hiçbir yerden erişemedim.", k:"teknoloji" },
  { t:"Yapay zekaya 'bana bir espri yap' dedim, kendi yazdığım bir espriyi geri söyledi, döngü böyle tamamlandı.", k:"teknoloji" },
  { t:"Ekran koruyucumu değiştirdim, üç gün sonra ekranı çatlattım, koruma teorik kalmış oldu.", k:"teknoloji" },
  { t:"Yeni router aldım, internet hızı aynı kaldı, para router'a gitti hıza değil.", k:"teknoloji" },
  { t:"Bilgisayarımda yüz sekme açık, hangisinde ne olduğunu bilmiyorum, dijital kaos böyle bir şey.", k:"teknoloji" },
  { t:"Telefonumun pil ömrü 'bir gün' yazıyordu kutuda, öğleden sonra şarj aramaya başladım, reklam bazen abartıyor.", k:"teknoloji" },
  { t:"Yeni bir kahve tarifi denedim, tarçın yerine yanlışlıkla karabiber attım, kahve şaşırtıcı bir yolculuğa çıktı.", k:"yemek" },
  { t:"Ekmek yapmaya karar verdim, maya eklemeyi unuttum, sonuç ekmek değil taş gibi bir şeydi.", k:"yemek" },
  { t:"Restoranda 'şef önerisi' sipariş ettim, gelen tabakta ne olduğunu anlamadım ama lezzetliydi, güven böyle oluşuyor.", k:"yemek" },
  { t:"Yemek pişirirken telefon çaldı, konuşmayı uzattım, döndüğümde tencere kömür üretmişti.", k:"yemek" },
  { t:"Salatalık turşusu yaptım, üç ay bekledi, açtığımda evin havası değişti, komşular bile fark etti.", k:"yemek" },
  { t:"Kahve fincanımı yıkarken kırdım, yeni fincan aldım, eskisinin tadı hâlâ damağımda.", k:"yemek" },
  { t:"Yeni diyet uygulaması indirdim, ilk gösterdiği yemek fotoğrafı acıktırdı, uygulama amacının tersini yaptı.", k:"yemek" },
  { t:"Mutfakta baharat şişelerinin kapağını karıştırdım, tarçın yerine kimyon koydum, tatlı beklenmedik bir tada büründü.", k:"yemek" },
  { t:"Balık pişirirken kokuyu önlemek için limon sıktım, ev hâlâ balık kokuyor ama limon da katkı yaptı sanırım.", k:"yemek" },
  { t:"Yeni tencere aldım, yapışmaz dediler, ilk yumurtada tersini kanıtladı.", k:"yemek" },
  { t:"Köpeğim yeni bir arkadaş edindi parkta, ben hâlâ komşularımın adını bilmiyorum, o sosyalleşmede önde.", k:"hayvanlar" },
  { t:"Kedim kutuya sığmadığı halde girmeye çalışıyor, umut her zaman fiziksel gerçeklerden büyük.", k:"hayvanlar" },
  { t:"Papağanım telefonun zil sesini taklit etti, üç kere telefona koştum, hepsi onun şakasıydı.", k:"hayvanlar" },
  { t:"Balığımın adını her gün unutuyorum, o da muhtemelen benim adımı bilmiyor, adil bir ilişki.", k:"hayvanlar" },
  { t:"Köpeğim yağmurda ıslanmayı seviyor, ben şemsiyeyle kaçıyorum, doğayla ilişkimiz çok farklı.", k:"hayvanlar" },
  { t:"Kaplumbağam bir köşeden diğerine geçti, üç gün sürdü, sabır dersini ondan almalıyım.", k:"hayvanlar" },
  { t:"Kedim yeni mobilyaları hemen tırmaladı, eskiler zaten tırmalanmıştı, tutarlılık önemli demek ki.", k:"hayvanlar" },
  { t:"Köpeğime komut öğretmeye çalıştım, o bana yeni bir komut öğretti, kim eğitiyor belli değil artık.", k:"hayvanlar" },
  { t:"Eşimle mobilya alışverişine çıktık, o beğendi ben beğenmedim, eve ikimizin de sevmediği bir şey geldi yine.", k:"iliskiler" },
  { t:"Kızım 'baba sen hep haklısın' dedi, gurur duydum, sonra para istediğini anladım.", k:"iliskiler" },
  { t:"Arkadaşım 'seninle gurur duyuyorum' dedi, ne başardığımı hâlâ bilmiyorum ama teşekkür ettim.", k:"iliskiler" },
  { t:"Annemle alışverişe çıktım, o her şeyi pahalı buldu, ben her şeyi ucuz buldum, tartışma büyüdü.", k:"iliskiler" },
  { t:"Eşim 'bugün nasıl geçti' diye sordu, anlatmaya başladım, o telefonuna baktı, klasik akşam sohbeti.", k:"iliskiler" },
  { t:"Kardeşimle aynı anda konuştuk, ikimiz de durmadı, kazanan olmadı ama ses kirliliği oldu.", k:"iliskiler" },
  { t:"Arkadaşım borç istedi, verdim, geri istemedim, dostluk bazen sessiz bir fedakarlık.", k:"iliskiler" },
  { t:"Otobüste telefonumu şarj etmeye çalıştım, priz yoktu, batarya da tükeniyordu, panik gerçekti.", k:"genel" },
  { t:"Sabah kahvaltı yaptım, işe geç kaldığımı fark edip yarısını yerken çıktım, mide de acele etti.", k:"genel" },
  { t:"Bugün erken yatacağım dedim, sonra dizinin yeni bölümü çıktı, plan orada değişti.", k:"genel" },
  { t:"Cüzdanımı kaybettim sandım, üç saat aradım, ceketimin cebinde buldum, panik gereksizmiş.", k:"genel" },
  { t:"Yeni bir hobi arıyorum dedim, internette araştırdım, üç saat sonra hâlâ araştırıyordum, o da bir hobi sayılır.", k:"genel" },
  { t:"Sabah spor yapacağım dedim, alarm kurmadım, kendimi test etmek istedim, test başarısız oldu.", k:"genel" },
  { t:"Markette kuyrukta beklerken kasadaki kişi kartını unuttu, sıra o kadar uzadı ki tatil planları yaptım kafamda.", k:"genel" },
  { t:"Öğretmenim 'herkes anladı mı' dedi, sınıf sessizce başını salladı, kimse gerçekten anlamamıştı.", k:"okul" },
  { t:"Kimya formülünü ezberledim ama sınavda harfleri karıştırdım, element tablosu bana küstü sanırım.", k:"okul" },
  { t:"Grup çalışmasında herkes farklı bir fikir söyledi, sonunda hiçbir fikri kullanmadık, demokrasi böyle işliyor.", k:"okul" },
  { t:"Sınav öncesi 'sakin ol' dedim kendime, kalemi elime alınca titremeye başladı, sakinlik teoride kaldı.", k:"okul" },
  { t:"Okulda beden dolabımı unuttum kombinasyonu, üç ay boyunca hademe açtı bana kapıyı.", k:"okul" },
  { t:"Öğretmen 'kim bu soruyu çözebilir' dedi, herkes defterine baktı sanki cevap orada yazıyormuş gibi.", k:"okul" },
  { t:"Yeni telefon kılıfı aldım, bir hafta sonra telefonu düşürdüm, kılıf da benimle beraber çatladı.", k:"teknoloji" },
  { t:"Uygulamalar için bildirim izni verdim, artık telefonum benden çok konuşuyor, sessizlik hakkım elimden alındı.", k:"teknoloji" },
  { t:"Yazıcıya kağıt yükledim, sıkıştı, teknoloji ilerledi ama yazıcılar hâlâ 90'larda yaşıyor.", k:"teknoloji" },
  { t:"Telefon rehberimde beş yüz kişi var, günde konuştuğum kişi sayısı bir, sosyal ağ teorik kalmış.", k:"teknoloji" },
  { t:"Yeni bir sosyal medya hesabı açtım, üç gün kullandım, dördüncü gün şifremi unuttum, kısa bir kariyer oldu.", k:"teknoloji" },
  { t:"Bilgisayarımın klavyesine kahve döktüm, birkaç tuş çalışmıyor artık, o kahvenin bedelini her yazıda ödüyorum.", k:"teknoloji" },
  { t:"Akıllı termostatım 'enerji tasarrufu' modunda beni dondurdu, tasarruf ile üşümek arasındaki çizgi ince.", k:"teknoloji" },
  { t:"Yemek tarifi videosunu izledim, kolay göründü, gerçekte mutfağı savaş alanına çevirdim.", k:"yemek" },
  { t:"Fırın saatini yanlış kurdum, kek yanık kokusuyla evi doldurdu, komşular pencere açtı.", k:"yemek" },
  { t:"Yeni bir çay markası denedim, paketin üstünde 'ferahlatıcı' yazıyordu, tadı eski ayakkabı gibiydi.", k:"yemek" },
  { t:"Kahvaltıda peynir çeşitlerini karıştırdım, hangisinin hangisi olduğunu artık bilmiyorum, damak tembelliği bu.", k:"yemek" },
  { t:"Yemek siparişi verirken not kısmına 'acısız olsun' yazdım, gelen yemek beni ağlattı, notlar okunmuyor galiba.", k:"yemek" },
  { t:"Dondurucudan et çıkardım, çözülmesini beklerken uyuyakaldım, akşam yemeği planı buzda kaldı.", k:"yemek" },
  { t:"Yeni bir mutfak robotu aldım, kullanma kılavuzunu okumadım, sonuç mutfakta küçük bir kaza oldu.", k:"yemek" },
  { t:"Kedim yeni halıyı hemen benimsedi, tırnaklarıyla imzasını attı, sanat eseri sayılır artık.", k:"hayvanlar" },
  { t:"Köpeğim ayna karşısında havladı, kendine tanışmak istedi belki, üç yıldır bu ritüel devam ediyor.", k:"hayvanlar" },
  { t:"Balığım suyun içinde bana bakıyor, ben ekrana bakıyorum, ikimiz de birbirimizden bir şey beklemiyoruz.", k:"hayvanlar" },
  { t:"Papağanım evde kimse yokken konuşuyor, kamerada izledim, kendi kendine sohbet ediyormuş, yalnız değilmiş meğer.", k:"hayvanlar" },
  { t:"Köpeğimin tasması koptu, yenisini aldım, o hâlâ eskisini arıyor gibi bakıyor, bağlılık güçlü bir duygu.", k:"hayvanlar" },
  { t:"Kedimi tartıya çıkardım, o tartıdan indi bir daha binmedi, kilosunu bilmemeyi tercih ediyor.", k:"hayvanlar" },
  { t:"Eşim 'bu hafta sonu dinleneceğiz' dedi, üç ev işi listesi çıkardı, dinlenme kelimesinin anlamı genişledi.", k:"iliskiler" },
  { t:"Arkadaşım 'seni özledim' dedi, buluşma teklif ettiğimde 'müsait değilim' dedi, özlem teorik kalmış.", k:"iliskiler" },
  { t:"Babamla maç izlerken aynı takımı tuttuk ama farklı oyuncuları eleştirdik, aile birliği böyle bir şey.", k:"iliskiler" },
  { t:"Kızıma masal okudum, o beni uyuttu, roller bazen tersine dönüyor.", k:"iliskiler" },
  { t:"Eşimle aynı diziyi izliyoruz ama o benden önce izliyor, spoiler vermemesi için yalvarıyorum her gün.", k:"iliskiler" },
  { t:"Arkadaşım 'sen değişmemişsin' dedi, iltifat mı eleştiri mi anlayamadım, gülümsedim güvenli tarafta kaldım.", k:"iliskiler" },
  { t:"Otobüs durağında telefonuma bakarken durağı geçtim, yürüyerek geri döndüm, spor programım böyle gelişti.", k:"genel" },
  { t:"Yeni bir alışkanlık edineceğim dedim, üç gün su içmeyi hatırladım, dördüncü gün eski düzenime döndüm.", k:"genel" },
  { t:"Sabah aynada saçımı düzeltmeye çalıştım, rüzgar dışarıda hepsini bozdu, emek boşa gitti.", k:"genel" },
  { t:"Yeni bir uygulamayla harcamalarımı takip ettim, ilk hafta iyiydi, ikinci hafta uygulamayı sildim gerçeği görmemek için.", k:"genel" },
  { t:"Kütüphanede sessizlik kuralı var, ben öksürünce herkes döndü baktı, ses kirliliği ben oldum.", k:"genel" },
  { t:"Bugün erken çıkacağım dedim işten, patronum tam o an toplantı çağırdı, plan orada suya düştü.", k:"genel" },
  { t:"Yeni spor ayakkabımı ilk kez giydim, yürürken gıcırdadı, herkes bana baktı sokakta, moda bazen ses getiriyor.", k:"genel" },
  { t:"Uzun zamandır aramadığım bir arkadaşımı aradım, telesekretere düştü, o da beni aramamış demek ki.", k:"iliskiler" },
  { t:"Kardeşimin evine misafirliğe gittim, yeğenim beni tanımadı, üç ay görüşmemenin bedeli buymuş.", k:"iliskiler" },
  { t:"Restoranda hesap gelince herkes telefonuna baktı, sessizlik dakikaları başladı, kimse ödemeyi teklif etmedi.", k:"yemek" },
  { t:"Yeni bir kahve dükkanı açıldı, fiyatları gördüm, kahve severliğimi sorguladım.", k:"yemek" },
  { t:"Köpeğim yeni komşunun kedisiyle tanıştı, ilk bakışta anlaşamadılar, komşuluk ilişkileri zorlu başladı.", k:"hayvanlar" },
  { t:"Kedim gece uyurken üstüme çıktı, uyanamadım ama nefes almakta zorlandım, sevgi ağırlığı bu kadar.", k:"hayvanlar" },
  { t:"Bilgisayar oyunu için yeni ekipman aldım, performans artmadı, sorun makinede değil oyuncudaymış.", k:"teknoloji" },
  { t:"Telefonuma yeni bir tema indirdim, iki gün sonra eski temaya döndüm, değişim zor bir şeymiş.", k:"teknoloji" },
  { t:"Sınavdan önce son kez tekrar yaptım, sınavda hiçbiri çıkmadı, çalıştığım konular başka bir evrende kaldı.", k:"okul" },
  { t:"Yemek tarifini takip ederken bir malzemeyi unuttum, sonuç farklı ama şaşırtıcı derecede yenebilirdi.", k:"yemek" },
  { t:"Yeni yıl için erken uyuma kararı aldım, ilk gece saat üçe kadar telefonla uğraştım, kararlılık işte böyle test edilir.", k:"genel" },
  { t:"Doktor 'su için bol bol' dedi, bardağı doldurdum, telefonla uğraşırken unuttum, bardak akşama kadar orada durdu.", k:"genel" },
  { t:"Öğretmenim 'sıradaki soruyu kim cevaplayacak' dedi, sınıfta herkes aynı anda yere baktı, sessizlik dile geldi.", k:"okul" }
];
