/* ============ ESPRİLER VERİSİ ============ */
const jokes = [
  { t:"Garson tabağı düşürünce müdür sormuş: 'Ne oldu?' Garson: 'Servis kesildi.'", k:"yemek" },
  { t:"Elektrikçiye 'nasılsın' demişler. 'Fişim prizde' demiş.", k:"teknoloji" },
  { t:"Terzi dükkanını neden kapatmış? İşleri artık dikiş tutmuyormuş.", k:"okul" },
  { t:"Balıkçıya neden kimse güvenmez? Her lafının içinde bir olta varmış.", k:"hayvanlar" },
  { t:"Fırıncı sınıfta kalan çocuğa demiş ki: 'Üzülme, sen de mayalanırsın.'", k:"okul" },
  { t:"Bilgisayar mühendisinin sevgilisi ondan neden ayrılmış? 'Bağlantı zaman aşımına uğradı' demiş.", k:"teknoloji" },
  { t:"Ekmek fırından çıkarken ne demiş? 'Artık hamur değilim, adamım!'", k:"yemek" },
  { t:"Matematik öğretmeni neden hep yalnızmış? Herkesi bir bilinmeyen sanırmış.", k:"okul" },
  { t:"Saatçiye 'işler nasıl' diye sormuşlar. 'Tık tık gidiyor' demiş.", k:"teknoloji" },
  { t:"Terziye 'nasılsın' demişler. 'İpin ucunu kaçırmadım' demiş.", k:"genel" },
  { t:"Fotoğrafçı neden hep pozitif konuşurmuş? Negatiften para kazandığı için.", k:"genel" },
  { t:"Elektrik faturasına neden kimse itiraz edemez? Son sözü hep o söylermiş.", k:"iliskiler" },
  { t:"Aşçıya dert anlatmışlar. 'Tuzla buz olsun' demiş.", k:"yemek" },
  { t:"Kuaföre 'ne var ne yok' diye sormuşlar. 'Saç var, dert yok' demiş.", k:"genel" },
  { t:"Bahçıvana 'işler nasıl' demişler. 'Kökünden hallediyorum' demiş.", k:"genel" },
  { t:"Tavuk yolun karşısına neden geçmiş? Marketteki tavuk indirimini kaçırmamak için.", k:"hayvanlar" },
  { t:"Pizzacıya 'nasıl kazanıyorsun' demişler. 'Dilim dilim' demiş.", k:"yemek" },
  { t:"Rüzgar gülüne fikrini sormuşlar. 'Duruma göre değişir' demiş.", k:"genel" },
  { t:"Kalem neden sınıfın gözdesiymiş? Herkesin notu onda saklıymış.", k:"okul" },
  { t:"Kaptana 'hiç yalan söyler misin' demişler. 'Rotamdan şaşmam' demiş.", k:"genel" },
  { t:"Kasap müşteriye neden hep gülermiş? Aralarında et kemik bir dostluk varmış.", k:"iliskiler" },
  { t:"Berbere 'politikaya ne dersin' demişler. 'Kısa keserim' demiş.", k:"genel" },
  { t:"Postacıya güvenirler miymiş? Evet, her şeyi zarfında saklarmış.", k:"genel" },
  { t:"Müzisyene bankayı sormuşlar. 'Nota biriktiririm, faiz değil' demiş.", k:"genel" },
  { t:"Marangoza yalan söyler misin demişler. 'Her lafımın altında tahta var' demiş.", k:"genel" },
  { t:"Trafik polisine neden herkes hak verir? Cezayı o yazdığı için.", k:"genel" },
  { t:"İki mıknatıs neden barışmış? Aralarında hâlâ çekim varmış.", k:"iliskiler" },
  { t:"Meteoroloğa güvenir misin demişler. 'Havadan sudan konuşmam' demiş.", k:"genel" },
  { t:"Kirpiye neden arkadaşı yokmuş? Sarılmaya çalışan herkesi batırırmış.", k:"hayvanlar" },
  { t:"Muhasebeciye dert anlatmışlar. 'Bir kalemde hallederim' demiş.", k:"okul" },
  { t:"Simitçiye güvenilir mi demişler. 'Delik tarafını göstermem' demiş.", k:"yemek" },
  { t:"Astronota tartışma sorulmuş. 'Yerçekimim yok, haklı çıkamam' demiş.", k:"genel" },
  { t:"Ayakkabı boyacısına 'dürüst müsün' demişler. 'Parlatırım ama üstünü örtmem' demiş.", k:"genel" },
  { t:"Manava güven sorulmuş. 'Çürüğü göstermem ama çürütmem de' demiş.", k:"genel" },
  { t:"Öğrenciye sınav nasıl geçti demişler. 'Bilmediğimden kaybedecek şeyim yoktu' demiş.", k:"okul" },
  { t:"Elektrikçi aşık olunca ne demiş? 'Aramızda akım var.'", k:"iliskiler" },
  { t:"İki anten neden hep barışıkmış? Sürekli birbirini çekermiş.", k:"iliskiler" },
  { t:"Kamera yalan söyler mi demişler. 'Her şeyi olduğu gibi çekerim' demiş.", k:"teknoloji" },
  { t:"Otobüs şoförüne güven sorulmuş. 'Kimseyi yolda bırakmam' demiş.", k:"genel" },
  { t:"İki saat neden hiç anlaşamazmış? Biri hep ileri, öbürü hep geri gidermiş.", k:"iliskiler" },
  { t:"Kahveye 'sırları saklar mısın' demişler. 'Dibine kadar inerim ama söylemem' demiş.", k:"genel" },
  { t:"Diş hekimine 'işler nasıl' demişler. 'Dişe diş gidiyor' demiş.", k:"genel" },
  { t:"Marangozun karısı ona neden kızmış? Her sözünü tahtaya vurduğu için.", k:"iliskiler" },
  { t:"Kasiyer neden hep haklıymış? Son rakamı o söylermiş.", k:"genel" },
  { t:"Kütüphaneciye 'nasıl geçinirsin' demişler. 'Hikayelere kulak veririm' demiş.", k:"okul" },
  { t:"İki telefon neden anlaşamamış? Şebekeleri hiç uyuşmamış.", k:"iliskiler" },
  { t:"Şoföre 'kavgadan uzak durur musun' demişler. 'Yolumu değiştiririm' demiş.", k:"genel" },
  { t:"Bahçıvana neden hep çiçeklerle konuşur demişler. 'Başka dinleyenim yok' demiş.", k:"genel" },
  { t:"Kuyumcuya güven sorulmuş. 'Her ilişkiyi altın değerinde tutarım' demiş.", k:"iliskiler" },
  { t:"Bakkala 'veresiye verir misin' demişler. 'Sadece güvene' demiş.", k:"genel" },
  { t:"İki bilgisayar neden evlenmiş? Aralarında güçlü bir bağlantı kurulmuş.", k:"teknoloji" },
  { t:"Şaire banka sorulmuş. 'Kafiyeyle para birikmiyor' demiş.", k:"genel" },
  { t:"Ressama 'boşluktan korkar mısın' demişler. 'Her boşluğu renklendiririm' demiş.", k:"genel" },
  { t:"Muhtara mahalle sorulmuş. 'Her taşını bilirim' demiş.", k:"genel" },
  { t:"Bilgisayar terapiye neden gitmiş? İçindeki dosyaları düzene sokmak için.", k:"teknoloji" },
  { t:"Ayna neden hiç yalan söylemez? Söyleyecek çok fazla yüzü olduğu için.", k:"genel" },
  { t:"Şaraba 'neden değerlisin' demişler. 'Beklemeyi bilirim' demiş.", k:"yemek" },
  { t:"Bilgisayar korsanına banka sorulmuş. 'Şifreleri tuzla buz ederim' demiş.", k:"teknoloji" },
  { t:"Kunduracıya güven sorulmuş. 'Herkesin ayak izini bilirim' demiş.", k:"genel" },
  { t:"Sinema salonuna 'neden herkes gelir' demişler. 'Herkesi büyük ekrana taşırım' demiş.", k:"genel" },
  { t:"Terazi burcuna karar sorulmuş. 'İki kefeyi de tartarım, karar başkasına kalır' demiş.", k:"iliskiler" },
  { t:"Denizciye 'hiç yalan söyler misin' demişler. 'Dümenimi kaptırmam' demiş.", k:"genel" },
  { t:"Optikçiye 'herkesle geçinir misin' demişler. 'Her olaya farklı gözle bakarım' demiş.", k:"iliskiler" },
  { t:"Terzi çırağı okulu neden bırakmış? Dikişleri tutmamış.", k:"okul" },
  { t:"Balon partiye neden gitmemiş? Havasında değilmiş.", k:"genel" },
  { t:"Buzdolabına 'hastasın' demişler. 'İçim soğuk, üşüttüm' demiş.", k:"yemek" },
  { t:"Kalem okula neden gitmiş? Kendini geliştirmek için.", k:"okul" },
  { t:"Pil polise neden gitmiş? Şarjı bitince suçlu hissetmiş.", k:"teknoloji" },
  { t:"Saat neden hep açmış? Sürekli tıklıyormuş.", k:"teknoloji" },
  { t:"Merdivene 'kimseyle konuşur musun' demişler. 'Basamak basamak giderim' demiş.", k:"okul" },
  { t:"Çamaşır makinesine 'dedikoducu musun' demişler. 'Her şeyi çalkalarım' demiş.", k:"teknoloji" },
  { t:"Yastık okula neden gitmemiş? Zaten yeterince ders almış.", k:"okul" },
  { t:"Kar tanesi neden yalnız kalmış? Kimse onunla eriyip gitmek istememiş.", k:"iliskiler" },
  { t:"Fil neden kırmızı gözlük takar? Yeşil gözlük bulamadığı için.", k:"hayvanlar" },
  { t:"Pizza terapiye neden gitmiş? Fazla dilimlenmiş de ondan.", k:"yemek" },
  { t:"Rüzgara 'neden hep yorgunsun' demişler. 'Sürekli esiyorum' demiş.", k:"genel" },
  { t:"Köpekler telefonu neden kullanamaz? Pati şifresini çözemedikleri için.", k:"hayvanlar" },
  { t:"Domatese 'neden kırmızısın' demişler. 'Salatalığın yeşilliğini kıskandım' demiş.", k:"yemek" },
  { t:"Hangi biber tatlıdır? Acı gerçekler değil de, tatlı biber.", k:"yemek" },
  { t:"Sıfır alan öğrenciye üzülme demişler. 'En azından değerim değişmedi' demiş.", k:"okul" },
  { t:"Asansör aşağı neden inmiş? Yukarıda sıkılmış.", k:"genel" },
  { t:"Ampul okula neden gitmiş? Parlak fikirler edinmek için.", k:"okul" },
  { t:"Klavyeye 'neden yorgunsun' demişler. 'Sürekli basılıyorum' demiş.", k:"teknoloji" },
  { t:"Süzgeç neden ağlamış? Her şey içinden kaçmış.", k:"yemek" },
  { t:"Hangi defter hiç bitmez? Borç defteri.", k:"genel" },
  { t:"Köfte futbol neden oynamış? Izgaraya gol atmak için.", k:"yemek" },
  { t:"Duvardaki resim neden düşmüş? Çiviyle arası bozulmuş.", k:"iliskiler" },
  { t:"En hızlı uçan sinek hangisi? Sinek-savar.", k:"hayvanlar" },
  { t:"Soba neden tütmüş? Keyfi yerindeymiş.", k:"genel" },
  { t:"Sözlüğe 'kendine güvenir misin' demişler. 'Bütün kelimeler arkamda' demiş.", k:"okul" },
  { t:"Tavaya 'neden ağlıyorsun' demişler. 'Hep yağ çekiliyor' demiş.", k:"yemek" },
  { t:"Cüzdana 'neden ağlıyorsun' demişler. 'İçimde yeşillik kalmadı' demiş.", k:"iliskiler" },
  { t:"En çok hangi ilimizde acı biber yenir? Kahraman-maraş.", k:"yemek" },
  { t:"İki muzdan biri düşmüş, diğeri ne demiş? 'Soyuldun işte.'", k:"yemek" },
  { t:"Hangi simit yenmez? Cansimidi.", k:"genel" },
  { t:"Hangi kalemle yazı yazılmaz? Kontrol kalemiyle.", k:"teknoloji" },
  { t:"Hangi anahtar hiçbir kapıyı açmaz? Sol anahtarı.", k:"okul" },
  { t:"Hangi fil uçabilir? Profil.", k:"genel" },
  { t:"Köpek balığına 'neden saldırdın' demişler. 'Dişim ağrıyor' demiş.", k:"hayvanlar" },
  { t:"Hangi perde hiç kapanmaz? Göz perdesi.", k:"genel" },
  { t:"En acı sos hangisi? Pişmanlık sosu.", k:"yemek" },
  { t:"Soru işaretine 'neden bükülmüşsün' demişler. 'Cevabı bulamadım' demiş.", k:"okul" },
  { t:"Hangi kartla alışveriş yapılmaz? Oyun kartıyla.", k:"genel" },
  { t:"Radyoya 'neden hiç susmazsın' demişler. 'Şarkı söylemeyi seviyorum' demiş.", k:"teknoloji" },
  { t:"Hangi köprüden geçilmez? Hayal köprüsünden.", k:"genel" },
  { t:"Hangi bağda üzüm yetişmez? Ayakkabı bağında.", k:"genel" },
  { t:"Kediler bilgisayarı neden sever? Fareyle oynamak için.", k:"hayvanlar" },
  { t:"Hangi tasla su içilmez? Kafatasıyla.", k:"genel" },
  { t:"Hangi makas saç kesmez? Yol makası.", k:"genel" },
  { t:"Makarna neden uzundur? Kısa olunca spagetti olamadığı için.", k:"yemek" },
  { t:"Kahve neden fincanda içilir? Bardaktan taşmasın diye.", k:"yemek" },
  { t:"En temiz deniz hangisi? Akdeniz.", k:"genel" },
  { t:"Hangi kuş hiç uçamaz? Tavuk.", k:"hayvanlar" },
  { t:"Hangi dalda çiçek açmaz? Bilim dalında.", k:"okul" },
  { t:"Hangi bardağa sıcak su konmaz? Kırık bardağa.", k:"yemek" },
  { t:"Hangi gün hiç bitmez? Bugün.", k:"genel" },
  { t:"Sivrisinek neden saz çalar? Davulu olmadığı için.", k:"hayvanlar" },
  { t:"En büyük örümcek hangisi? Ağ kuran örümcek.", k:"hayvanlar" },
  { t:"Hangi yelkenli hiç gitmez? Rüzgarsız yelkenli.", k:"genel" },
  { t:"Defter kaleme ne demiş? 'Bana çok ağır geliyorsun.'", k:"okul" },
  { t:"En yaramaz rüzgar hangisi? Kasırga.", k:"genel" },
  { t:"Hangi topaç hiç dönmez? Kırık topaç.", k:"genel" },
  { t:"Hangi tencerenin kapağı yoktur? Dipsiz tencerenin.", k:"yemek" },
  { t:"Hangi yol hiç bitmez? Sonsuz yol.", k:"genel" },
  { t:"Mıknatıs demiri neden çeker? Aralarında güçlü bir çekim olduğu için.", k:"teknoloji" },
  { t:"Hangi kilit hiç açılmaz? Paslı kilit.", k:"genel" },
  { t:"Hangi ağacın gölgesi yoktur? Hayal ağacının.", k:"genel" },
  { t:"En çalışkan böcek hangisi? Karınca.", k:"hayvanlar" },
  { t:"Hangi çorba hiç soğumaz? Kaynayan çorba.", k:"yemek" },
  { t:"En sessiz kütüphane hangisi? Kitapların uyuduğu kütüphane.", k:"okul" },
  { t:"Hangi filin hortumu yoktur? Profilin.", k:"genel" },
  { t:"Hangi yaprak hiç dökülmez? Plastik yaprak.", k:"genel" },
  { t:"Hangi kuş hiç ötmez? Oyuncak kuş.", k:"hayvanlar" },
  { t:"Tren neden düdük çalar? 'Yoldan çekilin' demek için.", k:"teknoloji" },
  { t:"Hangi nehir hiç akmaz? Donmuş nehir.", k:"genel" },
  { t:"Hangi dalda kuş ötmez? Kırık dalda.", k:"hayvanlar" },
  { t:"Hangi çöl en soğuktur? Kar yağan kutup çölü.", k:"genel" },
  { t:"Hangi kalem en uzun süre yazar? Hiç açılmamış olanı.", k:"okul" },
  { t:"Hangi kedi miyavlamaz? Oyuncak kedi.", k:"hayvanlar" },
  { t:"Hangi anahtar müzik çalar? Sol anahtarı.", k:"okul" },
  { t:"Hangi saat hiç şaşmaz? Duran saat, günde iki kez doğruyu gösterir.", k:"teknoloji" },
  { t:"Hangi bisküvi en serttir? Taş gibi olanı.", k:"yemek" },
  { t:"Kelebek neden kısa yaşar? Güzelliği solmasın diye.", k:"hayvanlar" },
  { t:"Hangi yol hiç kıvrılmaz? Cetvelle çizilen yol.", k:"genel" },
  { t:"Hangi tırnak hiç uzamaz? Vida tırnağı.", k:"genel" },
  { t:"Hangi ev hiç rüzgar almaz? Yer altı evi.", k:"genel" },
  { t:"Hangi havuzda su yoktur? Top havuzunda.", k:"genel" },
  { t:"Hangi sabun köpürmez? Kuru sabun.", k:"genel" },
  { t:"Hangi fener pil istemez? Deniz feneri.", k:"teknoloji" },
  { t:"En akıllı telefon hangisi? Sahibi akıllı olan telefon.", k:"teknoloji" },
  { t:"Hangi tencere hiç yemek pişirmez? Oyuncak tencere.", k:"yemek" },
  { t:"Hangi radyo hiç ses çıkarmaz? Kapalı radyo.", k:"teknoloji" },
  { t:"Hangi çiçek saksıda büyümez? Yapay çiçek.", k:"genel" },
  { t:"Hangi biletle trene binilmez? Sinema biletiyle.", k:"genel" },
  { t:"Hangi iplikle dikiş dikilmez? Örümcek ipliğiyle.", k:"genel" },
  { t:"Hangi eldiven sıcak tutmaz? Ameliyat eldiveni.", k:"genel" },
  { t:"Hangi harita hiç yer göstermez? Yanlış çizilmiş harita.", k:"okul" },
  { t:"Hangi mektup hiç postalanmaz? Elektronik mektup.", k:"teknoloji" },
  { t:"Mıknatıs tahtayı neden çekmez? Demir olmadığı için.", k:"teknoloji" },
  { t:"Hangi şapka başı korumaz? Delik şapka.", k:"genel" },
  { t:"Hangi defter hiç yırtılmaz? Dijital defter.", k:"teknoloji" },
  { t:"Hangi kapıdan hiç geçilmez? Çizilmiş kapıdan.", k:"genel" },

  { t:"Hangi araba hiç yol almaz? Oyuncak araba.", k:"genel" },
  { t:"Marangoza 'kavga eder misin' demişler. 'Rendelerim ama kırmam' demiş.", k:"genel" },
  { t:"Ütücüye 'sinirlenir misin' demişler. 'Her şeyi düzeltirim' demiş.", k:"genel" },
  { t:"Hangi çanta hiç eşya taşımaz? Göz çantası.", k:"genel" },
  { t:"Terazi bozulunca ne demiş? 'Artık kimseyi tartamıyorum.'", k:"genel" },
  { t:"Hangi para hiç harcanmaz? Oyun parası.", k:"genel" },
  { t:"Balona 'neden şişkin konuşuyorsun' demişler. 'Havamdayım' demiş.", k:"genel" },
  { t:"Hangi diş hiç ağrımaz? Tarak dişi.", k:"genel" },
  { t:"Kaplumbağaya 'neden geç kaldın' demişler. 'Kabuğuma çekildim' demiş.", k:"hayvanlar" },
  { t:"Hangi kol hiç yorulmaz? Sandalye kolu.", k:"genel" },
  { t:"Bulut yağmur yağdırınca ne demiş? 'İçimi döktüm rahatladım.'", k:"genel" },
  { t:"Hangi ayak hiç yürümez? Masa ayağı.", k:"genel" },
  { t:"Terziye 'boşandın mı' demişler. 'Hayır, sadece dikişi söktüm' demiş.", k:"iliskiler" },
  { t:"Hangi baş hiç düşünmez? Sarımsak başı.", k:"yemek" },
  { t:"Kalemtıraşa 'işin nasıl' demişler. 'Ucundan tutuyorum' demiş.", k:"okul" },
  { t:"Hangi kart hiç oynanmaz? Kimlik kartı.", k:"genel" },
  { t:"Kapıya 'neden gıcırdıyorsun' demişler. 'Yağlanmak istiyorum' demiş.", k:"genel" },
  { t:"Hangi burun hiç koku almaz? İbrik burnu.", k:"genel" },
  { t:"Termometreye 'neden üzgünsün' demişler. 'Her zaman derecem ölçülüyor' demiş.", k:"genel" },
  { t:"Hangi kanat hiç uçmaz? Bina kanadı.", k:"genel" },
  { t:"İki iğneye 'neden barışıksınız' demişler. 'Aynı yastıkta batıyoruz' demiş.", k:"iliskiler" },
  { t:"Hangi göz hiç görmez? İğne gözü.", k:"genel" },
  { t:"Terziye 'zengin misin' demişler. 'Her elbiseden pay alıyorum' demiş.", k:"genel" },
  { t:"Hangi el hiç tutmaz? Saat eli.", k:"teknoloji" },
  { t:"Bardak kırılınca ne demiş? 'Artık dolu değilim, parçalıyım.'", k:"yemek" },
  { t:"Hangi dil hiç konuşmaz? Ayakkabı dili.", k:"genel" },
  { t:"Terziye 'neden hiç yalnız değilsin' demişler. 'Her elbisede biri var' demiş.", k:"iliskiler" },
  { t:"Hangi kulak hiç duymaz? Testi kulağı.", k:"yemek" },
  { t:"Anahtar kilide 'neden hep haklısın' demişler. 'Son sözü ben söylerim' demiş.", k:"iliskiler" },
  { t:"Hangi burun hiç kanamaz? Gemi burnu.", k:"genel" },
  { t:"Şemsiyeye 'neden açıksın' demişler. 'Yağmurdan korkmuyorum' demiş.", k:"genel" },
  { t:"Hangi yüz hiç gülmez? Saat yüzü.", k:"teknoloji" },
  { t:"Fincan tabağa 'seni seviyorum' demiş. Tabak da 'ben de seni taşıyorum' demiş.", k:"iliskiler" },
  { t:"Hangi kalp hiç atmaz? Elma kalbi.", k:"yemek" },
  { t:"Kitaba 'neden sessizsin' demişler. 'Sayfa sayfa konuşurum' demiş.", k:"okul" },
  { t:"Hangi omuz hiç taşımaz? Yol omuzu.", k:"genel" },
  { t:"Merdivene 'neden yükseliyorsun' demişler. 'Basamak basamak ilerliyorum' demiş.", k:"genel" },
  { t:"Hangi bel hiç ağrımaz? Dağ beli.", k:"genel" },
  { t:"Sabuna 'neden köpürüyorsun' demişler. 'Temiz kalmayı seviyorum' demiş.", k:"genel" },
  { t:"Hangi damar hiç kanamaz? Maden damarı.", k:"genel" },
  { t:"Traktöre 'neden yorulmuyorsun' demişler. 'Toprağı severim' demiş.", k:"genel" },
  { t:"Hangi kabuk hiç kırılmaz? Yer kabuğu.", k:"genel" },
  { t:"Süpürgeye 'neden herkesle konuşursun' demişler. 'Ortalığı temizlerim' demiş.", k:"genel" },
  { t:"Hangi tel hiç kopmaz? Ses teli.", k:"genel" },
  { t:"Ütüye 'neden sıcaksın' demişler. 'Kırışıklıkları severim' demiş.", k:"genel" },
  { t:"Hangi diken hiç batmaz? Deniz dikeni.", k:"hayvanlar" },
  { t:"Sabahlığa 'neden rahatsın' demişler. 'Sabahları özgürüm' demiş.", k:"genel" },
  { t:"Hangi kanat hiç yorulmaz? Değirmen kanadı.", k:"genel" },
  { t:"Yastığa 'neden yumuşaksın' demişler. 'Güzel rüyalar isterim' demiş.", k:"genel" },
  { t:"Hangi baş hiç yorulmaz? İğne başı.", k:"genel" },
  { t:"Saate 'neden hep koşuyorsun' demişler. 'Zamanla yarışıyorum' demiş.", k:"teknoloji" },
  { t:"Hangi gözlük hiç görmez? Güneş gözlüğü kutuda.", k:"genel" },
  { t:"Kalemtıraşa 'kime kızıyorsun' demişler. 'Küt kalemlere' demiş.", k:"okul" },
  { t:"Hangi kapı hiç açılmaz? Resimdeki kapı.", k:"genel" },
  { t:"Fırçaya 'neden herkesi düzeltiyorsun' demişler. 'Saçları severim' demiş.", k:"genel" },
  { t:"Hangi tekerlek hiç dönmez? Kaderin tekerleği bazen.", k:"genel" },
  { t:"Radyatöre 'neden kızgınsın' demişler. 'Kışın işim var' demiş.", k:"genel" },
  { t:"Hangi kanat hiç açılmaz? Kapalı pencerenin kanadı.", k:"genel" },
  { t:"Musluğa 'neden ağlıyorsun' demişler. 'Damlıyorum' demiş.", k:"genel" },
  { t:"Hangi çatal hiç yemek yemez? Elektrik çatalı.", k:"teknoloji" },
  { t:"Prize 'neden hep bağlısın' demişler. 'Enerjimi kaybetmek istemiyorum' demiş.", k:"teknoloji" },
  { t:"Hangi ayna hiç yansıtmaz? Kırık ayna.", k:"genel" },
  { t:"Buzluğa 'neden soğuksun' demişler. 'Sıcaktan hoşlanmam' demiş.", k:"yemek" },
  { t:"Hangi yürek hiç çarpmaz? Enginar yüreği.", k:"yemek" },
  { t:"Fenere 'neden karanlıktan korkmuyorsun' demişler. 'Işığım var' demiş.", k:"genel" },
  { t:"Hangi göz hiç kırpılmaz? Fırtına gözü.", k:"genel" },
  { t:"Tabağa 'neden boşsun' demişler. 'Herkes beni boşaltır' demiş.", k:"yemek" },
  { t:"Hangi kulp hiç tutulmaz? Kapı kulpu gece.", k:"genel" },
  { t:"Kaşığa 'neden herkesle içlisin' demişler. 'Çorbayı severim' demiş.", k:"yemek" },
  { t:"Hangi yaprak hiç sararmaz? Zeytin yaprağı barışta.", k:"genel" },
  { t:"Vantilatöre 'neden hep dönüyorsun' demişler. 'Serinlemeyi seviyorum' demiş.", k:"teknoloji" },
  { t:"Hangi kaynak hiç kurumaz? Bilgi kaynağı.", k:"okul" },
  { t:"Cetvele 'neden hep doğrusun' demişler. 'Eğri büğrü sevmem' demiş.", k:"okul" },
  { t:"Hangi silgi hiç iz bırakmaz? Yeni silgi.", k:"okul" },
  { t:"Zile 'neden hep bağırıyorsun' demişler. 'Duyulmak istiyorum' demiş.", k:"genel" },
  { t:"Hangi ip hiç kopmaz? Umut ipi.", k:"genel" },
  { t:"Cama 'neden buğulanıyorsun' demişler. 'Sıcak nefes gördüm' demiş.", k:"genel" },
  { t:"Hangi kova hiç dolmaz? Delik kova.", k:"genel" },
  { t:"Kazana 'neden kaynıyorsun' demişler. 'Sabırsızım' demiş.", k:"yemek" },
  { t:"Hangi kuyu hiç susamaz? Petrol kuyusu.", k:"genel" },
  { t:"Bacaya 'neden tütüyorsun' demişler. 'İçim rahat' demiş.", k:"genel" },
  { t:"Hangi çekiç hiç çakmaz? Oyuncak çekiç.", k:"genel" },
  { t:"Kilide 'neden inatçısın' demişler. 'Doğru anahtarı bekliyorum' demiş.", k:"iliskiler" },
  { t:"Hangi vida hiç sökülmez? Paslı vida bazen.", k:"genel" },
  { t:"Testereye 'neden gıcırdıyorsun' demişler. 'İşim var kesecek' demiş.", k:"genel" },
  { t:"Hangi çivi hiç eğrilmez? Yeni çivi.", k:"genel" },
  { t:"Elektrik direğine 'yalnız mısın' demişler. 'Tellerle bağlıyım' demiş.", k:"iliskiler" },
  { t:"Hangi bulut hiç yağmur getirmez? Pamuk bulutu resimde.", k:"genel" },
  { t:"Güneşe 'neden hep gülersin' demişler. 'Işığımı esirgemem' demiş.", k:"genel" },
  { t:"Hangi yıldız hiç kaymaz? Deniz yıldızı.", k:"hayvanlar" },
  { t:"Aya 'neden hep değişiyorsun' demişler. 'Her gece farklı hissediyorum' demiş.", k:"genel" },
  { t:"Hangi rüzgar hiç esmez? Çöl sessizliğinde geçen rüzgar bazen.", k:"genel" },
  { t:"Yıldıza 'neden parlıyorsun' demişler. 'Karanlıktan korkmuyorum' demiş.", k:"genel" },
  { t:"Hangi deniz hiç dalgalanmaz? Sakin göl aslında deniz değil.", k:"genel" },
  { t:"Nehre 'neden hep akıyorsun' demişler. 'Durmayı bilmem' demiş.", k:"genel" },
  { t:"Hangi dağ hiç yükselmez? Çöp dağı.", k:"genel" },
  { t:"Volkana 'neden kızgınsın' demişler. 'İçimde çok şey birikti' demiş.", k:"genel" },
  { t:"Hangi ateş hiç sönmez? Aşk ateşi bazen sönmezmiş.", k:"iliskiler" },
  { t:"Kibrite 'neden kısa yaşarsın' demişler. 'Bir kez parlarım yeter' demiş.", k:"genel" },
  { t:"Hangi mum hiç erimez? Plastik mum.", k:"genel" },
  { t:"Işığa 'neden hep koşuyorsun' demişler. 'Karanlıktan hızlıyım' demiş.", k:"genel" },
  { t:"Hangi gölge hiç kaybolmaz? Geçmişin gölgesi bazen kaybolmaz.", k:"genel" },
  { t:"Aynaya 'yalan söyler misin' demişler. 'Gördüğümü söylerim' demiş.", k:"genel" },
  { t:"Hangi resim hiç solmaz? Hafızadaki resim.", k:"genel" },
  { t:"Fotoğrafa 'neden susarsın' demişler. 'Bir anı zaten anlatırım' demiş.", k:"genel" },
  { t:"Hangi çerçeve hiç boş kalmaz? Dolu anıların çerçevesi.", k:"genel" },
  { t:"Tabloya 'neden hareketsizsin' demişler. 'Zamanı durdurdum' demiş.", k:"genel" },
  { t:"Hangi fırça hiç boyamaz? Diş fırçası.", k:"genel" },
  { t:"Palete 'kaç renk taşırsın' demişler. 'Ne kadar hayal o kadar renk' demiş.", k:"genel" },
  { t:"Hangi kalem hiç silinmez? Dövme kalemi.", k:"genel" },
  { t:"Deftere 'neden hep açıksın' demişler. 'Sırlarımı saklamam' demiş.", k:"okul" },
  { t:"Hangi sayfa hiç çevrilmez? Son sayfa hep çevrilmez, kitap biter.", k:"okul" },
  { t:"Silgiye 'neden herkes seni sever' demişler. 'Hataları affederim' demiş.", k:"okul" },
  { t:"Hangi harf hiç okunmaz? Sessiz harf değil, gizli yazı.", k:"okul" },
  { t:"Noktaya 'neden küçüksün' demişler. 'Ama cümleyi bitiririm' demiş.", k:"okul" },
  { t:"Hangi çanta hiç kapanmaz? Açık büfe çantası.", k:"genel" },
  { t:"Sırt çantasına 'ağır mısın' demişler. 'Kitap dolu olunca evet' demiş.", k:"okul" },
  { t:"Hangi bilet hiç yırtılmaz? Şans bileti bazen hiç yırtılmaz kazanınca.", k:"genel" },
  { t:"Otobüs durağına 'neden hep beklersin' demişler. 'Sabrım bol' demiş.", k:"genel" },
  { t:"Hangi tekerlek hiç patlamaz? Yedek tekerlek kutuda.", k:"genel" },
  { t:"Direksiyona 'neden hep dönüyorsun' demişler. 'Yolu takip ederim' demiş.", k:"genel" },
  { t:"Hangi far hiç yanmaz? Bozuk far.", k:"genel" },
  { t:"Klaksona 'neden bağırırsın' demişler. 'Dikkat çekmek istiyorum' demiş.", k:"genel" },
  { t:"Hangi anahtar kontak hiç çalışmaz? Bitmiş akülü arabanın anahtarı.", k:"teknoloji" },
  { t:"Yakıt göstergesine 'neden endişelisin' demişler. 'Az kaldığımda haber veririm' demiş.", k:"genel" },
  { t:"Hangi lastik hiç şişmez? Delik lastik.", k:"genel" },
  { t:"Köprüye 'neden hiç düşmezsin' demişler. 'Sağlam ayaklarım var' demiş.", k:"genel" },
  { t:"Hangi tünel hiç karanlık kalmaz? Işıklı tünel.", k:"genel" },
  { t:"Trafik ışığına 'neden kırmızısın' demişler. 'Sabır zamanı geldi' demiş.", k:"genel" },
  { t:"Hangi işaret hiç değişmez? Dur işareti hep aynı kalır.", k:"genel" },
  { t:"Yaya geçidine 'neden çizgilisin' demişler. 'Herkesi güvenle geçiririm' demiş.", k:"genel" },
  { t:"Hangi durak hiç boş kalmaz? Kalabalık şehrin otobüs durağı.", k:"genel" },
  { t:"Bilet gişesine 'neden herkesle konuşursun' demişler. 'İşim insan görmek' demiş.", k:"genel" }
];
